/**
 * Shared helpers for the i18n scripts.
 *
 * English (src/i18n/en.ts) is the source of truth. Each language in
 * src/i18n/languages.json gets src/i18n/<code>.ts. src/i18n/.hashes.json
 * remembers which English text each translation was made from, so only new
 * or changed strings are ever sent for translation.
 *
 * Node 22.6+/24 runs the .ts dictionaries directly (type stripping).
 */

import { createHash } from 'node:crypto';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

export const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
export const I18N_DIR = join(ROOT, 'src', 'i18n');
const HASHES_FILE = join(I18N_DIR, '.hashes.json');

export const languages = () => JSON.parse(readFileSync(join(I18N_DIR, 'languages.json'), 'utf8'));

export async function loadDict(code) {
    const file = join(I18N_DIR, `${code}.ts`);
    if (!existsSync(file)) return null;
    const mod = await import(pathToFileURL(file).href + `?t=${Date.now()}`);
    return mod[code] || null;
}

export const hash = (text) => createHash('sha1').update(text).digest('hex').slice(0, 12);

export const placeholders = (text) => [...String(text).matchAll(/\{(\w+)\}/g)].map((m) => m[1]).sort().join(',');

export function loadHashes() {
    return existsSync(HASHES_FILE) ? JSON.parse(readFileSync(HASHES_FILE, 'utf8')) : {};
}

export function saveHashes(hashes) {
    const sorted = Object.fromEntries(Object.keys(hashes).sort().map((k) => [k, hashes[k]]));
    writeFileSync(HASHES_FILE, JSON.stringify(sorted, null, 2) + '\n');
}

/**
 * Compare one language against English.
 *   todo:    keys never translated, or whose English changed since translation
 *   adopted: keys already translated but not yet in .hashes.json (recorded as up to date)
 */
export function diffLanguage(en, dict, langHashes) {
    const todo = [];
    const adopted = [];
    const badPlaceholders = [];
    for (const [key, text] of Object.entries(en)) {
        const current = hash(text);
        if (!dict || dict[key] === undefined) {
            todo.push(key);
        } else if (langHashes[key] === undefined) {
            adopted.push(key);
        } else if (langHashes[key] !== current) {
            todo.push(key);
        }
        if (dict && dict[key] !== undefined && placeholders(dict[key]) !== placeholders(text)) badPlaceholders.push(key);
    }
    return { todo, adopted, badPlaceholders };
}

const esc = (s) => String(s).replace(/\\/g, '\\\\').replace(/'/g, "\\'").replace(/\n/g, '\\n');

/** Write src/i18n/<code>.ts in English key order; extra keys not in English are kept at the end */
export function writeDict(code, en, dict, meta) {
    const lines = [];
    for (const key of Object.keys(en)) if (dict[key] !== undefined) lines.push(`    '${esc(key)}': '${esc(dict[key])}',`);
    const extra = Object.keys(dict).filter((k) => !(k in en));
    if (extra.length) {
        lines.push('', '    // No longer in en.ts (kept, unused)');
        for (const key of extra) lines.push(`    '${esc(key)}': '${esc(dict[key])}',`);
    }
    const header = `/**\n * ${meta.name} (${meta.label}) — generated by \`npm run i18n:translate\` from en.ts.\n * Edit freely: a hand edit is kept until the English text for that key changes.\n */\n`;
    writeFileSync(
        join(I18N_DIR, `${code}.ts`),
        `${header}import type { Dictionary } from './en';\n\nexport const ${code}: Dictionary = {\n${lines.join('\n')}\n};\n`,
    );
}
