CREATE TABLE IF NOT EXISTS active_roles ("id" BIGSERIAL PRIMARY KEY, "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "enable" SMALLINT NOT NULL DEFAULT 1, "user_id" BIGINT NOT NULL, "role_id" BIGINT NOT NULL);

CREATE TABLE IF NOT EXISTS advance_bookings ("id" BIGSERIAL PRIMARY KEY, "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "enable" SMALLINT NOT NULL DEFAULT 1, "listing_id" BIGINT NOT NULL, "buyer_id" BIGINT NOT NULL, "farmer_id" BIGINT NOT NULL, "quantity_booked" DECIMAL(10,2) NOT NULL, "price_per_unit" DECIMAL(10,2) NOT NULL, "total_amount" DECIMAL(10,2) NOT NULL, "advance_payment_percent" INTEGER NOT NULL DEFAULT 20, "advance_payment_amount" DECIMAL(10,2) NOT NULL, "booking_date" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, "expected_delivery_date" TIMESTAMP NOT NULL, "status" VARCHAR(50) NOT NULL DEFAULT 'pending', "quality_standards" TEXT NULL, "contract_terms" TEXT NULL);

CREATE TABLE IF NOT EXISTS ai_usage_quota ("id" BIGSERIAL PRIMARY KEY, "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "enable" SMALLINT NOT NULL DEFAULT 1, "user_id" BIGINT NOT NULL, "date" DATE NOT NULL, "gps_enhanced_requests" INTEGER NOT NULL DEFAULT 0, "pincode_requests" INTEGER NOT NULL DEFAULT 0, "last_reset" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, "quota_limit" INTEGER NOT NULL DEFAULT 20);

CREATE TABLE IF NOT EXISTS annual_strategies ("id" BIGSERIAL PRIMARY KEY, "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "enable" SMALLINT NOT NULL DEFAULT 1, "farm_id" BIGINT NOT NULL, "farmer_id" BIGINT NOT NULL, "year" INTEGER NOT NULL, "kharif_crop" VARCHAR(255) NULL, "kharif_profit_estimate" DECIMAL(12,2) NULL, "kharif_confidence_score" DECIMAL(3,2) NULL, "rabi_crop" VARCHAR(255) NULL, "rabi_profit_estimate" DECIMAL(12,2) NULL, "rabi_confidence_score" DECIMAL(3,2) NULL, "zaid_crop" VARCHAR(255) NULL, "zaid_profit_estimate" DECIMAL(12,2) NULL, "zaid_confidence_score" DECIMAL(3,2) NULL, "total_annual_profit" DECIMAL(12,2) NULL, "implementation_timeline" TEXT NULL, "alternative_options" TEXT NULL, "risk_mitigation" TEXT NULL, "bedrock_response" TEXT NULL, "status" VARCHAR(255) DEFAULT 'draft');

CREATE TABLE IF NOT EXISTS breeding_records ("id" BIGSERIAL PRIMARY KEY, "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "enable" SMALLINT NOT NULL DEFAULT 1, "livestock_id" BIGINT NOT NULL, "farmer_id" BIGINT NOT NULL, "breeding_type" VARCHAR(50) NOT NULL, "breeding_date" DATE NOT NULL, "mate_id" BIGINT NULL, "mate_breed" VARCHAR(255) NULL, "expected_delivery_date" DATE NULL, "actual_delivery_date" DATE NULL, "pregnancy_status" VARCHAR(50) NOT NULL DEFAULT 'pending', "number_of_offspring" INTEGER NULL, "breeding_cost" DECIMAL(10,2) NULL, "veterinarian_name" VARCHAR(255) NULL, "notes" TEXT NULL);

CREATE TABLE IF NOT EXISTS buyer_interests ("id" BIGSERIAL PRIMARY KEY, "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "enable" SMALLINT NOT NULL DEFAULT 1, "listing_id" BIGINT NOT NULL, "buyer_name" VARCHAR(255) NOT NULL, "buyer_phone" VARCHAR(255) NOT NULL, "buyer_email" VARCHAR(255) NULL, "buyer_type" VARCHAR(255) NOT NULL, "interested_quantity" INTEGER NOT NULL, "message" TEXT NULL, "status" VARCHAR(255) DEFAULT 'pending', "delivery_latitude" DECIMAL(10,8) NULL, "delivery_longitude" DECIMAL(11,8) NULL, "delivery_pincode" VARCHAR(10) NULL, "delivery_state" VARCHAR(100) NULL, "delivery_district" VARCHAR(100) NULL, "delivery_village" VARCHAR(100) NULL, "delivery_address_line" VARCHAR(255) NULL);

CREATE TABLE IF NOT EXISTS crops ("id" BIGSERIAL PRIMARY KEY, "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "enable" SMALLINT NOT NULL DEFAULT 1, "farm_plot_id" BIGINT NOT NULL, "strategy_id" BIGINT NULL, "crop_name" VARCHAR(255) NOT NULL, "crop_variety" VARCHAR(255) NULL, "season" VARCHAR(255) NOT NULL, "planting_date" DATE NOT NULL, "expected_harvest_date" DATE NOT NULL, "area" DECIMAL(10,2) NOT NULL, "expected_yield" DECIMAL(12,2) NULL, "expected_profit" DECIMAL(12,2) NULL, "actual_yield" DECIMAL(12,2) NULL, "actual_profit" DECIMAL(12,2) NULL, "status" VARCHAR(255) DEFAULT 'planned', "parent_crop_id" BIGINT NULL, "crop_role" VARCHAR(20) DEFAULT 'main');

CREATE TABLE IF NOT EXISTS crop_diagnoses ("id" BIGSERIAL PRIMARY KEY, "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "enable" SMALLINT NOT NULL DEFAULT 1, "user_id" BIGINT NOT NULL, "crop_id" BIGINT NULL, "farm_id" BIGINT NULL, "crop_name" VARCHAR(100) NULL, "state" VARCHAR(100) NULL, "district" VARCHAR(100) NULL, "disease_name" VARCHAR(255) NULL, "scientific_name" VARCHAR(255) NULL, "category" VARCHAR(30) NULL, "severity" VARCHAR(20) NULL, "urgency" VARCHAR(20) NULL, "confidence" DECIMAL(4,3) NULL, "language" VARCHAR(10) NULL, "model_used" VARCHAR(100) NULL, "safety_flags" INTEGER NOT NULL DEFAULT 0, "result" JSONB NULL);

CREATE TABLE IF NOT EXISTS crop_expenses ("id" BIGSERIAL PRIMARY KEY, "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "enable" SMALLINT NOT NULL DEFAULT 1, "crop_id" BIGINT NOT NULL, "category" VARCHAR(255) NOT NULL, "amount" DECIMAL(12,2) NOT NULL, "description" TEXT NULL, "expense_date" DATE NOT NULL);

CREATE TABLE IF NOT EXISTS crop_market_data ("id" BIGSERIAL PRIMARY KEY, "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "enable" SMALLINT NOT NULL DEFAULT 1, "crop_name" VARCHAR(255) NOT NULL, "state" VARCHAR(255) NOT NULL, "district" VARCHAR(255) NULL, "price_per_kg" DECIMAL(10,2) NOT NULL, "date" DATE NOT NULL, "season" VARCHAR(255) NOT NULL, "yoy_growth" DECIMAL(5,2) NULL, "demand_level" VARCHAR(255) NULL);

CREATE TABLE IF NOT EXISTS crop_milestones ("id" BIGSERIAL PRIMARY KEY, "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "enable" SMALLINT NOT NULL DEFAULT 1, "crop_id" BIGINT NOT NULL, "stage" VARCHAR(255) NOT NULL, "expected_start_date" DATE NOT NULL, "expected_end_date" DATE NOT NULL, "actual_start_date" DATE NULL, "actual_end_date" DATE NULL, "status" VARCHAR(255) DEFAULT 'pending', "progress_percentage" INTEGER DEFAULT 0, "recommendations" TEXT NULL, "notes" TEXT NULL, "alert_sent" SMALLINT DEFAULT 0);

CREATE TABLE IF NOT EXISTS crop_profitability ("id" BIGSERIAL PRIMARY KEY, "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "enable" SMALLINT NOT NULL DEFAULT 1, "crop_type" VARCHAR(100) NOT NULL, "variety" VARCHAR(200) NULL, "state" VARCHAR(100) NOT NULL, "district" VARCHAR(100) NULL, "year" INTEGER NOT NULL, "season" VARCHAR(50) NULL, "avg_profit_per_acre" DECIMAL(10,2) NOT NULL, "min_profit_per_acre" DECIMAL(10,2) NULL, "max_profit_per_acre" DECIMAL(10,2) NULL, "seed_cost" DECIMAL(10,2) NULL, "fertilizer_cost" DECIMAL(10,2) NULL, "pesticide_cost" DECIMAL(10,2) NULL, "labor_cost" DECIMAL(10,2) NULL, "irrigation_cost" DECIMAL(10,2) NULL, "equipment_cost" DECIMAL(10,2) NULL, "other_costs" DECIMAL(10,2) NULL, "total_investment_cost" DECIMAL(10,2) NULL, "avg_revenue_per_acre" DECIMAL(10,2) NULL, "roi_percentage" DECIMAL(5,2) NULL, "break_even_yield" DECIMAL(10,2) NULL, "profit_margin" DECIMAL(5,2) NULL, "risk_level" VARCHAR(20) NULL, "price_risk_score" DECIMAL(3,2) NULL, "yield_risk_score" DECIMAL(3,2) NULL, "market_demand" VARCHAR(20) NULL, "competition_level" VARCHAR(20) NULL, "data_source" VARCHAR(100) NULL, "sample_size" INTEGER NULL);

CREATE TABLE IF NOT EXISTS farms ("id" BIGSERIAL PRIMARY KEY, "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "enable" SMALLINT NOT NULL DEFAULT 1, "name" VARCHAR(255) NOT NULL, "description" TEXT NULL, "location_state" VARCHAR(100) NOT NULL, "location_district" VARCHAR(100) NOT NULL, "location_block" VARCHAR(100) NULL, "location_village" VARCHAR(100) NULL, "latitude" DECIMAL(10,8) NULL, "longitude" DECIMAL(11,8) NULL, "total_area" DECIMAL(10,2) NOT NULL, "cultivable_area" DECIMAL(10,2) NULL, "area_unit" VARCHAR(20) NULL, "primary_soil_type" VARCHAR(50) NULL, "soil_ph" DECIMAL(3,1) NULL, "soil_characteristics" JSONB NULL, "irrigation_type" VARCHAR(50) NULL, "water_availability" VARCHAR(50) NULL, "previous_crops" TEXT[] NULL, "farming_experience_years" INTEGER NULL, "investment_capacity_per_acre" DECIMAL(10,2) NULL, "farm_profile_embedding" vector(512) NULL, "is_active" BOOLEAN NULL DEFAULT true, "is_verified" BOOLEAN NULL DEFAULT false, "nitrogen" DECIMAL(10,2) NULL, "phosphorus" DECIMAL(10,2) NULL, "potassium" DECIMAL(10,2) NULL, "ph_level" DECIMAL(4,2) NULL, "organic_carbon" DECIMAL(5,2) NULL, "electrical_conductivity" DECIMAL(5,2) NULL, "sulfur" DECIMAL(10,2) NULL, "zinc" DECIMAL(10,2) NULL, "iron" DECIMAL(10,2) NULL, "boron" DECIMAL(10,2) NULL, "copper" DECIMAL(10,2) NULL, "manganese" DECIMAL(10,2) NULL, "soil_depth_class" VARCHAR(50) NULL, "slope_class" VARCHAR(50) NULL, "erosion_class" VARCHAR(50) NULL, "soil_texture_class" VARCHAR(50) NULL, "land_capability_class" VARCHAR(10) NULL, "land_irrigability_class" VARCHAR(10) NULL, "hydrological_soil_group" VARCHAR(10) NULL, "shc_data_source" VARCHAR(100) NULL, "shc_fetched_at" TIMESTAMP NULL, "shc_partial_data" BOOLEAN NULL DEFAULT false, "shc_unavailable_styles" TEXT[] NULL, "user_id" BIGINT NOT NULL, "owner_id" BIGINT NOT NULL);

CREATE TABLE IF NOT EXISTS farm_plots ("id" BIGSERIAL PRIMARY KEY, "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "enable" SMALLINT NOT NULL DEFAULT 1, "farm_id" BIGINT NOT NULL, "plot_name" VARCHAR(255) NOT NULL, "area" DECIMAL(10,2) NOT NULL, "soil_type" VARCHAR(255) NOT NULL, "irrigation_type" VARCHAR(255) NOT NULL, "state" VARCHAR(255) NOT NULL, "district" VARCHAR(255) NOT NULL, "previous_crops" VARCHAR(255) NULL, "investment_capacity" DECIMAL(12,2) NULL, "nitrogen" DECIMAL(10,2) NULL, "phosphorus" DECIMAL(10,2) NULL, "potassium" DECIMAL(10,2) NULL, "ph_level" DECIMAL(4,2) NULL, "organic_carbon" DECIMAL(5,2) NULL, "electrical_conductivity" DECIMAL(5,2) NULL, "sulfur" DECIMAL(10,2) NULL, "zinc" DECIMAL(10,2) NULL, "iron" DECIMAL(10,2) NULL, "boron" DECIMAL(10,2) NULL);

CREATE TABLE IF NOT EXISTS fertilizer_applications ("id" BIGSERIAL PRIMARY KEY, "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "enable" SMALLINT NOT NULL DEFAULT 1, "farm_id" BIGINT NOT NULL, "plot_id" BIGINT NULL, "crop_id" BIGINT NULL, "application_date" DATE NOT NULL, "fertilizer_type" VARCHAR(100) NOT NULL, "category" VARCHAR(50) NOT NULL, "quantity_kg" DECIMAL(10,2) NOT NULL, "quantity_per_hectare" DECIMAL(10,2) NULL, "area_applied_hectares" DECIMAL(10,2) NULL, "nitrogen_kg" DECIMAL(10,2) NULL, "phosphorus_kg" DECIMAL(10,2) NULL, "potassium_kg" DECIMAL(10,2) NULL, "cost_total" DECIMAL(10,2) NULL, "cost_per_kg" DECIMAL(10,2) NULL, "cost_per_hectare" DECIMAL(10,2) NULL, "application_method" VARCHAR(255) NULL, "growth_stage" VARCHAR(100) NULL, "days_after_planting" BIGINT NULL, "soil_test_before_id" BIGINT NULL, "soil_test_after_id" BIGINT NULL, "effectiveness_score" DECIMAL(5,2) NULL, "soil_response_notes" TEXT NULL, "weather_conditions" VARCHAR(255) NULL, "temperature_celsius" DECIMAL(5,2) NULL, "rainfall_mm_24h" DECIMAL(6,2) NULL, "recommended_by" VARCHAR(255) NULL, "recommendation_id" VARCHAR(255) NULL, "notes" TEXT NULL);

CREATE TABLE IF NOT EXISTS historical_yields ("id" BIGSERIAL PRIMARY KEY, "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "enable" SMALLINT NOT NULL DEFAULT 1, "crop_type" VARCHAR(100) NOT NULL, "variety" VARCHAR(200) NULL, "state" VARCHAR(100) NOT NULL, "district" VARCHAR(100) NULL, "block" VARCHAR(100) NULL, "year" INTEGER NOT NULL, "season" VARCHAR(50) NULL, "avg_yield_per_acre" DECIMAL(10,2) NOT NULL, "min_yield" DECIMAL(10,2) NULL, "max_yield" DECIMAL(10,2) NULL, "success_rate" DECIMAL(5,2) NULL, "farmer_count" INTEGER NULL, "total_area_cultivated" DECIMAL(12,2) NULL, "soil_types" JSONB NULL, "irrigation_methods" JSONB NULL, "avg_rainfall" DECIMAL(8,2) NULL, "avg_temperature" DECIMAL(5,2) NULL, "quality_distribution" JSONB NULL, "avg_quality_grade" VARCHAR(10) NULL, "data_source" VARCHAR(100) NULL, "data_quality_score" DECIMAL(3,2) NULL);

CREATE TABLE IF NOT EXISTS livestock ("id" BIGSERIAL PRIMARY KEY, "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "enable" SMALLINT NOT NULL DEFAULT 1, "farm_id" BIGINT NOT NULL, "farmer_id" BIGINT NOT NULL, "species" VARCHAR(255) NOT NULL, "breed" VARCHAR(255) NOT NULL, "name" VARCHAR(100) NULL, "quantity" INTEGER NOT NULL DEFAULT 1, "purchase_price" DECIMAL(12,2) NOT NULL, "purchase_date" DATE NOT NULL, "purpose" VARCHAR(255) NOT NULL, "expected_roi" DECIMAL(12,2) NULL, "break_even_date" DATE NULL, "status" VARCHAR(255) DEFAULT 'active', "latitude" DECIMAL(10,8) NULL, "longitude" DECIMAL(11,8) NULL, "pincode" VARCHAR(10) NULL, "state" VARCHAR(100) NULL, "district" VARCHAR(100) NULL, "village" VARCHAR(100) NULL, "address_line" VARCHAR(255) NULL);

CREATE TABLE IF NOT EXISTS livestock_health_records ("id" BIGSERIAL PRIMARY KEY, "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "enable" SMALLINT NOT NULL DEFAULT 1, "livestock_id" BIGINT NOT NULL, "record_type" VARCHAR(255) NOT NULL, "record_date" DATE NOT NULL, "description" TEXT NOT NULL, "veterinarian_name" VARCHAR(255) NULL, "cost" DECIMAL(10,2) NULL, "next_due_date" DATE NULL, "notes" TEXT NULL);

CREATE TABLE IF NOT EXISTS livestock_listings ("id" BIGSERIAL PRIMARY KEY, "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "enable" SMALLINT NOT NULL DEFAULT 1, "livestock_id" BIGINT NOT NULL, "farmer_id" BIGINT NOT NULL, "title" VARCHAR(255) NOT NULL, "description" TEXT NULL, "species" VARCHAR(100) NOT NULL, "breed" VARCHAR(255) NOT NULL, "age_years" INTEGER NULL, "age_months" INTEGER NULL, "gender" VARCHAR(50) NOT NULL, "quantity" INTEGER NOT NULL DEFAULT 1, "purpose" VARCHAR(100) NOT NULL, "price" DECIMAL(12,2) NOT NULL, "price_negotiable" SMALLINT DEFAULT 1, "weight_kg" DECIMAL(10,2) NULL, "health_status" VARCHAR(100) DEFAULT 'healthy', "vaccination_status" VARCHAR(100) NULL, "last_vaccination_date" DATE NULL, "milk_production_liters" DECIMAL(10,2) NULL, "breeding_certified" SMALLINT DEFAULT 0, "breeding_certification_number" VARCHAR(255) NULL, "genetic_lineage" TEXT NULL, "photos" TEXT NULL, "videos" TEXT NULL, "location_state" VARCHAR(100) NOT NULL, "location_district" VARCHAR(100) NOT NULL, "location_village" VARCHAR(100) NULL, "latitude" DECIMAL(10,8) NULL, "longitude" DECIMAL(11,8) NULL, "pincode" VARCHAR(10) NULL, "address_line" VARCHAR(255) NULL, "farmer_contact_phone" VARCHAR(20) NULL, "farmer_contact_email" VARCHAR(255) NULL, "status" VARCHAR(50) DEFAULT 'active', "views_count" INTEGER DEFAULT 0, "interest_count" INTEGER DEFAULT 0, "inquiry_count" INTEGER DEFAULT 0, "featured" SMALLINT DEFAULT 0, "featured_until" TIMESTAMP NULL);

CREATE TABLE IF NOT EXISTS livestock_marketplace_listings ("id" BIGSERIAL PRIMARY KEY, "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "enable" SMALLINT NOT NULL DEFAULT 1, "livestock_id" BIGINT NOT NULL, "farmer_id" BIGINT NOT NULL, "listing_type" VARCHAR(255) NOT NULL, "asking_price" DECIMAL(12,2) NOT NULL, "current_age_months" INTEGER NOT NULL, "current_weight_kg" DECIMAL(10,2) NULL, "milk_production_liters_per_day" DECIMAL(10,2) NULL, "breeding_history" TEXT NULL, "health_status" VARCHAR(255) DEFAULT 'excellent', "vaccination_status" VARCHAR(255) DEFAULT 'up_to_date', "total_investment" DECIMAL(12,2) NOT NULL, "total_revenue" DECIMAL(12,2) DEFAULT 0, "current_roi_percentage" DECIMAL(10,2) NULL, "break_even_achieved" SMALLINT DEFAULT 0, "break_even_date" DATE NULL, "projected_annual_profit" DECIMAL(12,2) NULL, "location_state" VARCHAR(255) NOT NULL, "location_district" VARCHAR(255) NOT NULL, "farmer_contact_phone" VARCHAR(255) NOT NULL, "farmer_contact_email" VARCHAR(255) NULL, "listing_status" VARCHAR(255) DEFAULT 'active', "views_count" INTEGER DEFAULT 0, "bedrock_analysis" TEXT NULL);

CREATE TABLE IF NOT EXISTS livestock_roi_predictions ("id" BIGSERIAL PRIMARY KEY, "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "enable" SMALLINT NOT NULL DEFAULT 1, "user_id" BIGINT NULL, "animal_id" BIGINT NULL, "prediction_date" DATE NOT NULL, "prediction_type" VARCHAR(50) NULL, "species" VARCHAR(50) NOT NULL, "breed" VARCHAR(100) NOT NULL, "age_months" INTEGER NULL, "purpose" VARCHAR(50) NOT NULL, "purchase_price" DECIMAL(10,2) NOT NULL, "initial_setup_cost" DECIMAL(10,2) NULL, "total_initial_investment" DECIMAL(10,2) NOT NULL, "monthly_feed_cost" DECIMAL(10,2) NOT NULL, "monthly_healthcare_cost" DECIMAL(10,2) NULL, "monthly_labor_cost" DECIMAL(10,2) NULL, "monthly_other_costs" DECIMAL(10,2) NULL, "total_monthly_cost" DECIMAL(10,2) NOT NULL, "monthly_milk_revenue" DECIMAL(10,2) NULL, "monthly_egg_revenue" DECIMAL(10,2) NULL, "monthly_wool_revenue" DECIMAL(10,2) NULL, "monthly_manure_revenue" DECIMAL(10,2) NULL, "total_monthly_revenue" DECIMAL(10,2) NULL, "offspring_revenue_per_year" DECIMAL(10,2) NULL, "expected_sale_value" DECIMAL(10,2) NULL, "expected_productive_years" INTEGER NULL, "break_even_months" INTEGER NOT NULL, "break_even_date" DATE NULL, "roi_1_year" DECIMAL(10,2) NULL, "roi_2_year" DECIMAL(10,2) NULL, "roi_5_year" DECIMAL(10,2) NULL, "roi_percentage_1_year" DECIMAL(5,2) NULL, "roi_percentage_2_year" DECIMAL(5,2) NULL, "roi_percentage_5_year" DECIMAL(5,2) NULL, "monthly_net_profit" DECIMAL(10,2) NULL, "annual_net_profit" DECIMAL(10,2) NULL, "lifetime_net_profit" DECIMAL(10,2) NULL, "comparison_with_alternatives" JSONB NULL, "market_price_trends" JSONB NULL, "risk_level" VARCHAR(20) NULL, "risk_factors" JSONB NULL, "mortality_risk" DECIMAL(5,2) NULL, "disease_risk" DECIMAL(5,2) NULL, "market_risk" DECIMAL(5,2) NULL, "confidence_score" DECIMAL(3,2) NULL, "key_assumptions" JSONB NULL, "sensitivity_analysis" JSONB NULL, "recommendation" TEXT NULL, "optimization_suggestions" JSONB NULL, "market_data_source" VARCHAR(100) NULL, "breed_performance_data_source" VARCHAR(100) NULL);

CREATE TABLE IF NOT EXISTS livestock_transactions ("id" BIGSERIAL PRIMARY KEY, "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "enable" SMALLINT NOT NULL DEFAULT 1, "listing_id" BIGINT NOT NULL, "seller_id" BIGINT NOT NULL, "buyer_id" BIGINT NOT NULL, "transaction_type" VARCHAR(50) NOT NULL, "quantity" INTEGER NOT NULL DEFAULT 1, "agreed_price" DECIMAL(12,2) NOT NULL, "status" VARCHAR(50) DEFAULT 'inquiry', "buyer_message" TEXT NULL, "seller_response" TEXT NULL, "buyer_contact_phone" VARCHAR(20) NULL, "buyer_contact_email" VARCHAR(255) NULL, "delivery_required" SMALLINT DEFAULT 0, "delivery_address" TEXT NULL, "delivery_latitude" DECIMAL(10,8) NULL, "delivery_longitude" DECIMAL(11,8) NULL, "health_guarantee_days" INTEGER DEFAULT 7, "health_guarantee_expires" TIMESTAMP NULL, "completed_at" TIMESTAMP NULL, "cancelled_at" TIMESTAMP NULL, "cancellation_reason" TEXT NULL, "notes" TEXT NULL);

CREATE TABLE IF NOT EXISTS market_prices ("id" BIGSERIAL PRIMARY KEY, "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "enable" SMALLINT NOT NULL DEFAULT 1, "listing_id" BIGINT NULL, "booking_id" BIGINT NULL, "transaction_id" BIGINT NULL, "item_type" VARCHAR(50) NOT NULL, "item_name" VARCHAR(255) NOT NULL, "variety" VARCHAR(255) NULL, "price_per_unit" DECIMAL(10,2) NOT NULL, "quantity" DECIMAL(10,2) NOT NULL, "total_value" DECIMAL(12,2) NOT NULL, "quality_grade" VARCHAR(10) NULL, "quality_premium_percent" DECIMAL(5,2) NULL, "state" VARCHAR(100) NOT NULL, "district" VARCHAR(100) NOT NULL, "transaction_date" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, "season" VARCHAR(50) NULL, "source" VARCHAR(50) NOT NULL);

CREATE TABLE IF NOT EXISTS marketplace_listings ("id" BIGSERIAL PRIMARY KEY, "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "enable" SMALLINT NOT NULL DEFAULT 1, "farm_id" BIGINT NOT NULL, "farmer_id" BIGINT NOT NULL, "crop_type" VARCHAR(255) NOT NULL, "crop_variety" VARCHAR(255) NULL, "expected_harvest_date" DATE NOT NULL, "estimated_quantity" INTEGER NOT NULL, "available_quantity" INTEGER NULL, "quality_grade" VARCHAR(255) NULL, "location_state" VARCHAR(255) NOT NULL, "location_district" VARCHAR(255) NOT NULL, "farmer_contact_phone" VARCHAR(255) NULL, "farmer_contact_email" VARCHAR(255) NULL, "status" VARCHAR(255) DEFAULT 'active', "delivery_latitude" DECIMAL(10,8) NULL, "delivery_longitude" DECIMAL(11,8) NULL, "delivery_pincode" VARCHAR(10) NULL, "delivery_village" VARCHAR(100) NULL, "delivery_address_line" VARCHAR(255) NULL, "embedding" vector(384) NULL, "embedding_cache_key" VARCHAR(255) NULL, "price_per_unit" DECIMAL(10,2) NULL);

CREATE TABLE IF NOT EXISTS msp_rates ("id" BIGSERIAL PRIMARY KEY, "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "enable" SMALLINT NOT NULL DEFAULT 1, "crop_name" VARCHAR(255) NOT NULL, "year" INTEGER NOT NULL, "season" VARCHAR(50) NOT NULL, "msp_per_quintal" DECIMAL(10,2) NOT NULL, "msp_per_kg" DECIMAL(10,2) NULL, "increase_over_previous" DECIMAL(5,2) NULL, "cost_of_production" DECIMAL(10,2) NULL, "return_over_cost_percent" DECIMAL(5,2) NULL, "source" VARCHAR(100) NULL);

CREATE TABLE IF NOT EXISTS ndap_downloaded_files ("id" BIGSERIAL PRIMARY KEY, "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "enable" SMALLINT NOT NULL DEFAULT 1, "file_name" VARCHAR(255) NOT NULL, "file_hash" VARCHAR(64) NOT NULL UNIQUE, "file_content" BYTEA NOT NULL);

CREATE TABLE IF NOT EXISTS ndap_ingestion_runs ("id" BIGSERIAL PRIMARY KEY, "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "enable" SMALLINT NOT NULL DEFAULT 1, "file_name" VARCHAR(255) NOT NULL, "file_hash" VARCHAR(64) NOT NULL UNIQUE, "started_at" TIMESTAMP NOT NULL, "completed_at" TIMESTAMP NULL, "status" VARCHAR(20) NOT NULL, "records_ingested" INTEGER NULL DEFAULT 0, "error_message" TEXT NULL);

CREATE TABLE IF NOT EXISTS offspring ("id" BIGSERIAL PRIMARY KEY, "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "enable" SMALLINT NOT NULL DEFAULT 1, "breeding_record_id" BIGINT NOT NULL, "livestock_id" BIGINT NULL, "farmer_id" BIGINT NOT NULL, "birth_date" DATE NOT NULL, "gender" VARCHAR(20) NULL, "birth_weight" DECIMAL(10,2) NULL, "health_status" VARCHAR(50) NOT NULL DEFAULT 'healthy', "current_weight" DECIMAL(10,2) NULL, "growth_rate" DECIMAL(10,2) NULL, "weaning_date" DATE NULL, "sale_date" DATE NULL, "sale_price" DECIMAL(12,2) NULL, "notes" TEXT NULL);

CREATE TABLE IF NOT EXISTS opportunity_costs ("id" BIGSERIAL PRIMARY KEY, "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "enable" SMALLINT NOT NULL DEFAULT 1, "location_state" VARCHAR(100) NOT NULL, "location_district" VARCHAR(100) NULL, "primary_crop" VARCHAR(100) NOT NULL, "alternative_crop" VARCHAR(100) NOT NULL, "season" VARCHAR(50) NULL, "year" INTEGER NULL, "primary_crop_profit" DECIMAL(10,2) NOT NULL, "alternative_crop_profit" DECIMAL(10,2) NOT NULL, "profit_difference" DECIMAL(10,2) NOT NULL, "primary_crop_investment" DECIMAL(10,2) NULL, "alternative_crop_investment" DECIMAL(10,2) NULL, "investment_difference" DECIMAL(10,2) NULL, "primary_crop_roi" DECIMAL(5,2) NULL, "alternative_crop_roi" DECIMAL(5,2) NULL, "roi_difference" DECIMAL(5,2) NULL, "primary_crop_risk" VARCHAR(20) NULL, "alternative_crop_risk" VARCHAR(20) NULL, "risk_factor" DECIMAL(3,2) NULL, "primary_crop_demand" VARCHAR(20) NULL, "alternative_crop_demand" VARCHAR(20) NULL, "market_stability_comparison" TEXT NULL, "recommended_choice" VARCHAR(100) NULL, "recommendation_confidence" DECIMAL(3,2) NULL, "recommendation_reasoning" TEXT NULL, "soil_suitability_comparison" JSONB NULL, "water_requirement_comparison" JSONB NULL, "labor_requirement_comparison" JSONB NULL);

CREATE TABLE IF NOT EXISTS payment_milestones ("id" BIGSERIAL PRIMARY KEY, "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "enable" SMALLINT NOT NULL DEFAULT 1, "booking_id" BIGINT NOT NULL, "milestone_type" VARCHAR(50) NOT NULL, "amount" DECIMAL(10,2) NOT NULL, "due_date" TIMESTAMP NOT NULL, "paid_date" TIMESTAMP NULL, "status" VARCHAR(50) NOT NULL DEFAULT 'pending', "payment_method" VARCHAR(100) NULL, "transaction_id" VARCHAR(255) NULL);

CREATE TABLE IF NOT EXISTS pest_disease_alerts ("id" BIGSERIAL PRIMARY KEY, "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "enable" SMALLINT NOT NULL DEFAULT 1, "crop_id" BIGINT NOT NULL, "farm_id" BIGINT NOT NULL, "pest_disease_name" VARCHAR(255) NOT NULL, "alert_type" VARCHAR(50) NOT NULL, "severity" VARCHAR(50) NOT NULL, "description" TEXT NOT NULL, "crop_stage" VARCHAR(100) NOT NULL, "weather_conditions" TEXT NULL, "organic_recommendations" TEXT NULL, "chemical_recommendations" TEXT NULL, "prevention_measures" TEXT NULL, "timing_instructions" TEXT NULL, "notification_sent" SMALLINT DEFAULT 0, "notification_sent_at" TIMESTAMP NULL, "is_resolved" SMALLINT DEFAULT 0, "resolved_at" TIMESTAMP NULL);

CREATE TABLE IF NOT EXISTS pest_disease_data ("id" BIGSERIAL PRIMARY KEY, "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "enable" SMALLINT NOT NULL DEFAULT 1, "name" VARCHAR(255) NOT NULL UNIQUE, "type" VARCHAR(50) NOT NULL, "scientific_name" VARCHAR(255) NULL, "description" TEXT NOT NULL, "affected_crops" TEXT NULL, "risk_stages" TEXT NULL, "temperature_min" DECIMAL(5,2) NULL, "temperature_max" DECIMAL(5,2) NULL, "humidity_min" INTEGER NULL, "humidity_max" INTEGER NULL, "rainfall_min" DECIMAL(6,2) NULL, "severity" VARCHAR(50) NOT NULL, "organic_treatments" TEXT NULL, "chemical_treatments" TEXT NULL, "prevention_measures" TEXT NULL, "timing_instructions" TEXT NULL, "data_source" VARCHAR(255) NULL, "last_updated" TIMESTAMP NULL);

CREATE TABLE IF NOT EXISTS price_predictions ("id" BIGSERIAL PRIMARY KEY, "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "enable" SMALLINT NOT NULL DEFAULT 1, "item_type" VARCHAR(50) NOT NULL, "item_name" VARCHAR(255) NOT NULL, "variety" VARCHAR(255) NULL, "state" VARCHAR(100) NOT NULL, "district" VARCHAR(100) NULL, "prediction_date" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, "target_date" DATE NOT NULL, "predicted_price" DECIMAL(10,2) NOT NULL, "confidence_score" DECIMAL(3,2) NOT NULL, "price_range_min" DECIMAL(10,2) NULL, "price_range_max" DECIMAL(10,2) NULL, "trend" VARCHAR(20) NULL, "demand_forecast" VARCHAR(20) NULL, "supply_forecast" VARCHAR(20) NULL, "season" VARCHAR(50) NULL, "model_version" VARCHAR(50) NULL, "factors" TEXT NULL);

CREATE TABLE IF NOT EXISTS push_subscriptions ("id" BIGSERIAL PRIMARY KEY, "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "enable" SMALLINT NOT NULL DEFAULT 1, "user_id" BIGINT NOT NULL, "endpoint" TEXT NOT NULL, "p256dh" VARCHAR(255) NOT NULL, "auth" VARCHAR(255) NOT NULL, "user_agent" VARCHAR(512) NULL);

CREATE TABLE IF NOT EXISTS quality_verifications ("id" BIGSERIAL PRIMARY KEY, "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "enable" SMALLINT NOT NULL DEFAULT 1, "booking_id" BIGINT NOT NULL, "verification_date" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, "verifier_type" VARCHAR(50) NOT NULL, "quality_grade" VARCHAR(10) NOT NULL, "quality_metrics" TEXT NULL, "photos" TEXT NULL, "passed" SMALLINT NOT NULL DEFAULT 0, "notes" TEXT NULL);

CREATE TABLE IF NOT EXISTS roles ("id" BIGSERIAL PRIMARY KEY, "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "enable" SMALLINT NOT NULL DEFAULT 1, "name" VARCHAR(255) NOT NULL);

CREATE TABLE IF NOT EXISTS satellite_observations ("id" BIGSERIAL PRIMARY KEY, "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "enable" SMALLINT NOT NULL DEFAULT 1, "farm_id" BIGINT NOT NULL, "scene_id" VARCHAR(120) NOT NULL, "observed_on" DATE NOT NULL, "source" VARCHAR(50) NOT NULL DEFAULT 'sentinel-2-l2a', "ndvi" DECIMAL(5,3) NULL, "ndmi" DECIMAL(5,3) NULL, "ndre" DECIMAL(5,3) NULL, "clear_pct" DECIMAL(5,1) NULL, "pixels" INTEGER NULL, "state" VARCHAR(100) NULL, "district" VARCHAR(100) NULL);

CREATE TABLE IF NOT EXISTS seasonal_trends ("id" BIGSERIAL PRIMARY KEY, "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "enable" SMALLINT NOT NULL DEFAULT 1, "crop_type" VARCHAR(100) NOT NULL, "state" VARCHAR(100) NOT NULL, "district" VARCHAR(100) NULL, "planting_season" VARCHAR(50) NOT NULL, "harvest_season" VARCHAR(50) NULL, "optimal_planting_start" DATE NULL, "optimal_planting_end" DATE NULL, "optimal_harvest_start" DATE NULL, "optimal_harvest_end" DATE NULL, "avg_growth_duration_days" INTEGER NULL, "price_trend_yoy" DECIMAL(5,2) NULL, "demand_trend_yoy" DECIMAL(5,2) NULL, "yield_trend_yoy" DECIMAL(5,2) NULL, "weather_suitability_score" DECIMAL(3,2) NULL, "pest_disease_risk" VARCHAR(20) NULL, "market_timing_score" DECIMAL(3,2) NULL, "avg_success_rate" DECIMAL(5,2) NULL, "farmer_adoption_rate" DECIMAL(5,2) NULL, "recommended_varieties" JSONB NULL, "companion_crops" JSONB NULL, "rotation_recommendations" JSONB NULL, "analysis_start_year" INTEGER NULL, "analysis_end_year" INTEGER NULL, "years_of_data" INTEGER NULL);

CREATE TABLE IF NOT EXISTS services ("id" BIGSERIAL PRIMARY KEY, "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "enable" SMALLINT NOT NULL DEFAULT 1, "category" VARCHAR(50) NOT NULL, "name" VARCHAR(255) NOT NULL, "organisation" VARCHAR(255) NULL, "description" TEXT NULL, "phone" VARCHAR(20) NOT NULL, "whatsapp" VARCHAR(20) NULL, "email" VARCHAR(255) NULL, "location_state" VARCHAR(100) NULL, "location_district" VARCHAR(100) NULL, "address" TEXT NULL, "languages" VARCHAR(100) NULL, "available_now" SMALLINT NOT NULL DEFAULT 1, "verified" SMALLINT NOT NULL DEFAULT 0, "is_active" SMALLINT NOT NULL DEFAULT 1, "added_by_user_id" BIGINT NULL, "user_id" BIGINT NULL);

CREATE TABLE IF NOT EXISTS shc_state_district_codes ("id" BIGSERIAL PRIMARY KEY, "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "enable" SMALLINT NOT NULL DEFAULT 1, "state_name" VARCHAR(100) NOT NULL, "state_code" INTEGER NOT NULL, "district_name" VARCHAR(100) NOT NULL, "district_code" INTEGER NOT NULL);

CREATE TABLE IF NOT EXISTS slusi_ingestion_runs ("id" BIGSERIAL PRIMARY KEY, "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "enable" SMALLINT NOT NULL DEFAULT 1, "started_at" TIMESTAMP NOT NULL, "completed_at" TIMESTAMP NULL, "status" VARCHAR(20) NOT NULL, "lcc_records_ingested" INTEGER NULL DEFAULT 0, "maps_ingested" INTEGER NULL DEFAULT 0, "error_message" TEXT NULL);

CREATE TABLE IF NOT EXISTS slusi_lcc_reports ("id" BIGSERIAL PRIMARY KEY, "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "enable" SMALLINT NOT NULL DEFAULT 1, "state" VARCHAR(100) NOT NULL, "district" VARCHAR(100) NOT NULL, "report_no" VARCHAR(50) NOT NULL, "year" INTEGER NULL, "total_area_ha" DECIMAL(14,2) NULL, "lcc_class_i" DECIMAL(14,2) NULL, "lcc_class_ii" DECIMAL(14,2) NULL, "lcc_class_iii" DECIMAL(14,2) NULL, "lcc_class_iv" DECIMAL(14,2) NULL, "lcc_class_v" DECIMAL(14,2) NULL, "lcc_class_vi" DECIMAL(14,2) NULL, "lcc_class_vii" DECIMAL(14,2) NULL, "lcc_class_viii" DECIMAL(14,2) NULL, "forest_area" DECIMAL(14,2) NULL, "miscellaneous_area" DECIMAL(14,2) NULL, "spatial_available" BOOLEAN NULL DEFAULT false, "non_spatial_available" BOOLEAN NULL DEFAULT false, "ingested_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);

CREATE TABLE IF NOT EXISTS slusi_microwatershed_maps ("id" BIGSERIAL PRIMARY KEY, "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "enable" SMALLINT NOT NULL DEFAULT 1, "state" VARCHAR(100) NOT NULL UNIQUE, "map_data" BYTEA NOT NULL, "file_size_bytes" INTEGER NULL, "ingested_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);

CREATE TABLE IF NOT EXISTS soil_amendments ("id" BIGSERIAL PRIMARY KEY, "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "enable" SMALLINT NOT NULL DEFAULT 1, "plot_id" BIGINT NOT NULL, "amendment_date" DATE NOT NULL, "amendment_type" VARCHAR(100) NOT NULL, "amendment_name" VARCHAR(200) NULL, "primary_purpose" VARCHAR(100) NULL, "target_improvement" JSONB NULL, "quantity" DECIMAL(10,2) NOT NULL, "unit" VARCHAR(20) NOT NULL, "quantity_per_acre" DECIMAL(10,2) NULL, "application_method" VARCHAR(100) NULL, "incorporation_depth" DECIMAL(5,2) NULL, "cost" DECIMAL(10,2) NULL, "cost_per_acre" DECIMAL(10,2) NULL, "organic_matter_content" DECIMAL(5,2) NULL, "nutrient_content" JSONB NULL, "carbon_nitrogen_ratio" DECIMAL(5,2) NULL, "current_ph" DECIMAL(3,1) NULL, "target_ph" DECIMAL(3,1) NULL, "expected_ph_change" DECIMAL(3,1) NULL, "days_before_planting" INTEGER NULL, "soil_moisture_at_application" VARCHAR(50) NULL, "weather_conditions" JSONB NULL, "expected_benefits" JSONB NULL, "expected_duration_months" INTEGER NULL, "actual_benefits" JSONB NULL, "effectiveness_rating" INTEGER NULL, "follow_up_soil_test_id" BIGINT NULL, "recommendation_source" VARCHAR(100) NULL, "recommended_by" VARCHAR(255) NULL, "notes" TEXT NULL);

CREATE TABLE IF NOT EXISTS soil_moisture_data ("id" BIGSERIAL PRIMARY KEY, "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "enable" SMALLINT NOT NULL DEFAULT 1, "state" VARCHAR(100) NOT NULL, "district" VARCHAR(100) NOT NULL, "date" DATE NOT NULL, "year" INTEGER NOT NULL, "month" VARCHAR(2) NOT NULL, "moisture_level" DECIMAL(10,4) NOT NULL, "agency_name" VARCHAR(255) NULL);

CREATE TABLE IF NOT EXISTS soil_tests ("id" BIGSERIAL PRIMARY KEY, "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "enable" SMALLINT NOT NULL DEFAULT 1, "plot_id" BIGINT NOT NULL, "test_date" DATE NOT NULL, "test_type" VARCHAR(100) NULL, "testing_lab" VARCHAR(255) NULL, "lab_report_url" VARCHAR(500) NULL, "soil_type" VARCHAR(50) NULL, "soil_texture" VARCHAR(50) NULL, "soil_color" VARCHAR(50) NULL, "ph_level" DECIMAL(3,1) NOT NULL, "electrical_conductivity" DECIMAL(6,2) NULL, "organic_carbon" DECIMAL(5,2) NULL, "organic_matter" DECIMAL(5,2) NULL, "nitrogen_n" DECIMAL(8,2) NULL, "phosphorus_p" DECIMAL(8,2) NULL, "potassium_k" DECIMAL(8,2) NULL, "calcium_ca" DECIMAL(8,2) NULL, "magnesium_mg" DECIMAL(8,2) NULL, "sulfur_s" DECIMAL(8,2) NULL, "iron_fe" DECIMAL(8,2) NULL, "manganese_mn" DECIMAL(8,2) NULL, "zinc_zn" DECIMAL(8,2) NULL, "copper_cu" DECIMAL(8,2) NULL, "boron_b" DECIMAL(8,2) NULL, "molybdenum_mo" DECIMAL(8,2) NULL, "nitrogen_status" VARCHAR(20) NULL, "phosphorus_status" VARCHAR(20) NULL, "potassium_status" VARCHAR(20) NULL, "water_holding_capacity" DECIMAL(5,2) NULL, "drainage_quality" VARCHAR(50) NULL, "bulk_density" DECIMAL(5,2) NULL, "porosity" DECIMAL(5,2) NULL, "microbial_activity" VARCHAR(50) NULL, "earthworm_count" INTEGER NULL, "overall_health_score" DECIMAL(3,2) NULL, "fertility_rating" VARCHAR(20) NULL, "lab_recommendations" TEXT NULL, "fertilizer_recommendations" JSONB NULL, "amendment_recommendations" JSONB NULL, "test_cost" DECIMAL(10,2) NULL);

CREATE TABLE IF NOT EXISTS soil_test_results ("id" BIGSERIAL PRIMARY KEY, "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "enable" SMALLINT NOT NULL DEFAULT 1, "farm_id" BIGINT NOT NULL, "plot_id" BIGINT NULL, "test_date" TIMESTAMP NOT NULL, "lab_name" VARCHAR(255) NULL, "lab_reference_number" VARCHAR(255) NULL, "nitrogen_kg_per_ha" DECIMAL(10,2) NULL, "phosphorus_kg_per_ha" DECIMAL(10,2) NULL, "potassium_kg_per_ha" DECIMAL(10,2) NULL, "ph_level" DECIMAL(4,2) NULL, "organic_carbon_percent" DECIMAL(5,2) NULL, "organic_matter_percent" DECIMAL(5,2) NULL, "electrical_conductivity" DECIMAL(6,2) NULL, "sulfur_ppm" DECIMAL(10,2) NULL, "zinc_ppm" DECIMAL(10,2) NULL, "iron_ppm" DECIMAL(10,2) NULL, "manganese_ppm" DECIMAL(10,2) NULL, "copper_ppm" DECIMAL(10,2) NULL, "boron_ppm" DECIMAL(10,2) NULL, "soil_health_score" DECIMAL(5,2) NULL, "test_method" VARCHAR(255) NULL, "raw_data_json" TEXT NULL, "recommendations" TEXT NULL, "notes" TEXT NULL);

CREATE TABLE IF NOT EXISTS supply_matches ("id" BIGSERIAL PRIMARY KEY, "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "enable" SMALLINT NOT NULL DEFAULT 1, "request_id" BIGINT NOT NULL, "listing_id" BIGINT NULL, "farmer_id" BIGINT NOT NULL, "matched_quantity" DECIMAL(10,2) NOT NULL, "match_score" DECIMAL(5,2) NULL, "price_offered" DECIMAL(10,2) NULL, "status" VARCHAR(50) NOT NULL DEFAULT 'suggested', "match_explanation" TEXT NULL, "is_aggregated" SMALLINT NOT NULL DEFAULT 0, "aggregation_group_id" VARCHAR(100) NULL, "farmer_confirmation_status" VARCHAR(50) NOT NULL DEFAULT 'pending', "farmer_confirmed_at" TIMESTAMP NULL, "buyer_accepted_at" TIMESTAMP NULL, "delivery_status" VARCHAR(50) NOT NULL DEFAULT 'pending', "delivery_notes" TEXT NULL);

CREATE TABLE IF NOT EXISTS supply_requests ("id" BIGSERIAL PRIMARY KEY, "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "enable" SMALLINT NOT NULL DEFAULT 1, "buyer_id" BIGINT NOT NULL, "crop_type" VARCHAR(100) NOT NULL, "quantity_needed" DECIMAL(10,2) NOT NULL, "quality_requirements" TEXT NULL, "delivery_date_start" TIMESTAMP NOT NULL, "delivery_date_end" TIMESTAMP NOT NULL, "max_price_per_unit" DECIMAL(10,2) NULL, "recurring" SMALLINT NOT NULL DEFAULT 0, "recurrence_pattern" TEXT NULL, "is_emergency" SMALLINT NOT NULL DEFAULT 0, "status" VARCHAR(50) NOT NULL DEFAULT 'open', "delivery_address" TEXT NULL, "delivery_latitude" DECIMAL(10,8) NULL, "delivery_longitude" DECIMAL(11,8) NULL, "delivery_pincode" VARCHAR(10) NULL, "delivery_state" VARCHAR(100) NULL, "delivery_district" VARCHAR(100) NULL, "notes" TEXT NULL, "embedding" vector(384) NULL, "embedding_cache_key" VARCHAR(255) NULL);

CREATE TABLE IF NOT EXISTS system_settings ("id" BIGSERIAL PRIMARY KEY, "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "enable" SMALLINT NOT NULL DEFAULT 1, "key" VARCHAR(255) NOT NULL UNIQUE, "value" TEXT NOT NULL, "description" TEXT NULL);

CREATE TABLE IF NOT EXISTS transport_bookings ("id" BIGSERIAL PRIMARY KEY, "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "enable" SMALLINT NOT NULL DEFAULT 1, "transaction_id" BIGINT NOT NULL, "provider_id" BIGINT NOT NULL, "requester_id" BIGINT NOT NULL, "pickup_address" TEXT NOT NULL, "pickup_latitude" DECIMAL(10,8) NULL, "pickup_longitude" DECIMAL(11,8) NULL, "delivery_address" TEXT NOT NULL, "delivery_latitude" DECIMAL(10,8) NULL, "delivery_longitude" DECIMAL(11,8) NULL, "distance_km" DECIMAL(10,2) NOT NULL, "livestock_type" VARCHAR(100) NOT NULL, "livestock_count" INTEGER NOT NULL, "animal_value" DECIMAL(12,2) NOT NULL, "transport_cost" DECIMAL(10,2) NOT NULL, "insurance_opted" SMALLINT DEFAULT 0, "insurance_cost" DECIMAL(10,2) NULL, "total_cost" DECIMAL(10,2) NOT NULL, "scheduled_pickup_date" TIMESTAMP NOT NULL, "estimated_delivery_date" TIMESTAMP NOT NULL, "actual_pickup_date" TIMESTAMP NULL, "actual_delivery_date" TIMESTAMP NULL, "status" VARCHAR(50) DEFAULT 'pending', "tracking_updates" TEXT NULL, "special_instructions" TEXT NULL, "rating" INTEGER NULL, "review" TEXT NULL, "reviewed_at" TIMESTAMP NULL, "cancelled_at" TIMESTAMP NULL, "cancellation_reason" TEXT NULL);

CREATE TABLE IF NOT EXISTS transport_providers ("id" BIGSERIAL PRIMARY KEY, "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "enable" SMALLINT NOT NULL DEFAULT 1, "user_id" BIGINT NOT NULL, "company_name" VARCHAR(255) NOT NULL, "contact_person" VARCHAR(255) NOT NULL, "contact_phone" VARCHAR(20) NOT NULL, "contact_email" VARCHAR(255) NULL, "service_areas" TEXT NOT NULL, "vehicle_types" TEXT NOT NULL, "livestock_specialization" TEXT NULL, "base_rate_per_km" DECIMAL(10,2) NOT NULL, "minimum_charge" DECIMAL(10,2) NOT NULL, "insurance_available" SMALLINT DEFAULT 0, "insurance_rate_percentage" DECIMAL(5,2) NULL, "max_capacity_animals" INTEGER NOT NULL, "rating" DECIMAL(3,2) DEFAULT 0, "total_ratings" INTEGER DEFAULT 0, "completed_transports" INTEGER DEFAULT 0, "verified" SMALLINT DEFAULT 0, "verification_documents" TEXT NULL, "license_number" VARCHAR(100) NULL, "status" VARCHAR(50) DEFAULT 'active');

CREATE TABLE IF NOT EXISTS users ("id" BIGSERIAL PRIMARY KEY, "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "enable" SMALLINT NOT NULL DEFAULT 1, "cognito_user_id" VARCHAR(255) UNIQUE NULL, "firebase_id" VARCHAR(255) UNIQUE NULL, "username" VARCHAR(100) NOT NULL, "name" VARCHAR(255) NOT NULL, "email" VARCHAR(255) UNIQUE NULL, "phone" VARCHAR(255) UNIQUE NULL, "google_id" VARCHAR(255) NULL, "facebook_id" VARCHAR(255) NULL, "password" VARCHAR(255) NULL, "user_type" VARCHAR(255) DEFAULT 'farmer', "preferred_language" VARCHAR(255) DEFAULT 'en', "mfa_enabled" SMALLINT DEFAULT 0, "latitude" DECIMAL(10,8) NULL, "longitude" DECIMAL(11,8) NULL, "pincode" VARCHAR(10) NULL, "state" VARCHAR(100) NULL, "district" VARCHAR(100) NULL, "village" VARCHAR(100) NULL, "address_line" VARCHAR(255) NULL, "is_active" SMALLINT DEFAULT 1, "is_verified" SMALLINT DEFAULT 0);

CREATE TABLE IF NOT EXISTS user_notifications ("id" BIGSERIAL PRIMARY KEY, "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "enable" SMALLINT NOT NULL DEFAULT 1, "user_id" BIGINT NOT NULL, "title" VARCHAR(255) NOT NULL, "message" TEXT NOT NULL, "type" VARCHAR(50) NOT NULL DEFAULT 'info', "link" VARCHAR(512) NULL, "data" JSONB NULL, "is_read" BOOLEAN NOT NULL DEFAULT false, "read_at" TIMESTAMP NULL);

CREATE TABLE IF NOT EXISTS veterinarians ("id" BIGSERIAL PRIMARY KEY, "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "enable" SMALLINT NOT NULL DEFAULT 1, "added_by_user_id" BIGINT NULL, "name" VARCHAR(255) NOT NULL, "clinic_name" VARCHAR(255) NULL, "specialization" VARCHAR(100) NULL, "species_supported" TEXT NULL, "phone" VARCHAR(20) NOT NULL, "whatsapp" VARCHAR(20) NULL, "email" VARCHAR(255) NULL, "location_state" VARCHAR(100) NULL, "location_district" VARCHAR(100) NULL, "address" TEXT NULL, "available_now" SMALLINT NOT NULL DEFAULT 1, "verified" SMALLINT NOT NULL DEFAULT 0, "rating" DECIMAL(3,2) DEFAULT 0, "total_ratings" INTEGER DEFAULT 0, "notes" TEXT NULL);

CREATE TABLE IF NOT EXISTS voice_assist_logs ("id" BIGSERIAL PRIMARY KEY, "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "enable" SMALLINT NOT NULL DEFAULT 1, "user_id" BIGINT NOT NULL, "source" VARCHAR(20) NOT NULL DEFAULT 'text', "task" VARCHAR(50) NULL, "ui_lang" VARCHAR(10) NULL, "language_detected" VARCHAR(10) NULL, "mime_type" VARCHAR(50) NULL, "audio_bytes" INTEGER NULL, "duration_ms" INTEGER NULL, "transcript" TEXT NULL, "intent" VARCHAR(20) NULL, "model_used" VARCHAR(100) NULL, "status" VARCHAR(20) NOT NULL DEFAULT 'ok', "error" TEXT NULL, "latency_ms" INTEGER NULL);

CREATE TABLE IF NOT EXISTS weather_alerts ("id" BIGSERIAL PRIMARY KEY, "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "enable" SMALLINT NOT NULL DEFAULT 1, "farm_id" BIGINT NULL, "state" VARCHAR(255) NOT NULL, "district" VARCHAR(255) NULL, "alert_type" VARCHAR(255) NOT NULL, "severity" VARCHAR(255) NOT NULL, "message" TEXT NOT NULL, "recommendation" TEXT NULL, "valid_from" TIMESTAMP NOT NULL, "valid_until" TIMESTAMP NOT NULL, "is_active" SMALLINT DEFAULT 1);

CREATE TABLE IF NOT EXISTS weather_forecasts ("id" BIGSERIAL PRIMARY KEY, "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "enable" SMALLINT NOT NULL DEFAULT 1, "latitude" DECIMAL(10,8) NOT NULL, "longitude" DECIMAL(11,8) NOT NULL, "location_name" VARCHAR(255) NULL, "state" VARCHAR(100) NULL, "district" VARCHAR(100) NULL, "forecast_date" DATE NOT NULL, "forecast_time" TIMESTAMP NULL, "forecast_type" VARCHAR(50) NULL, "temperature_min" DECIMAL(5,2) NULL, "temperature_max" DECIMAL(5,2) NULL, "temperature_avg" DECIMAL(5,2) NULL, "feels_like" DECIMAL(5,2) NULL, "rainfall_probability" DECIMAL(5,2) NULL, "rainfall_amount" DECIMAL(8,2) NULL, "rainfall_intensity" VARCHAR(50) NULL, "wind_speed" DECIMAL(6,2) NULL, "wind_direction" VARCHAR(50) NULL, "wind_gust" DECIMAL(6,2) NULL, "humidity" DECIMAL(5,2) NULL, "pressure" DECIMAL(8,2) NULL, "dew_point" DECIMAL(5,2) NULL, "cloud_cover" DECIMAL(5,2) NULL, "visibility" DECIMAL(6,2) NULL, "uv_index" DECIMAL(4,2) NULL, "solar_radiation" DECIMAL(8,2) NULL, "weather_condition" VARCHAR(100) NULL, "weather_description" TEXT NULL, "weather_icon" VARCHAR(50) NULL, "evapotranspiration" DECIMAL(6,2) NULL, "soil_moisture_index" DECIMAL(5,2) NULL, "growing_degree_days" DECIMAL(6,2) NULL, "data_source" VARCHAR(100) NULL, "source_forecast_id" VARCHAR(255) NULL, "data_quality_score" DECIMAL(3,2) NULL, "fetched_at" TIMESTAMP NULL, "expires_at" TIMESTAMP NULL);