"""Add remaining tables for market intelligence, soil health, weather, livestock, and marketplace

Revision ID: d35ffb77671d
Revises: 001
Create Date: 2026-02-22 16:32:23.147946

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision = 'd35ffb77671d'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crop_market_data',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('crop_type', sa.String(length=100), nullable=False),
    sa.Column('variety', sa.String(length=200), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('market_name', sa.String(length=200), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.Column('season', sa.String(length=50), nullable=True),
    sa.Column('avg_price_per_quintal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('min_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('max_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('modal_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('market_demand_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('supply_volume', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('price_volatility', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('price_trend', sa.String(length=20), nullable=True),
    sa.Column('yoy_price_change', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('mom_price_change', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('data_source', sa.String(length=100), nullable=True),
    sa.Column('data_quality_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_crop_location_time', 'crop_market_data', ['crop_type', 'state', 'district', 'year', 'month'], unique=False)
    op.create_index('idx_season_location', 'crop_market_data', ['season', 'state', 'year'], unique=False)
    op.create_index(op.f('ix_crop_market_data_crop_type'), 'crop_market_data', ['crop_type'], unique=False)
    op.create_index(op.f('ix_crop_market_data_district'), 'crop_market_data', ['district'], unique=False)
    op.create_index(op.f('ix_crop_market_data_month'), 'crop_market_data', ['month'], unique=False)
    op.create_index(op.f('ix_crop_market_data_season'), 'crop_market_data', ['season'], unique=False)
    op.create_index(op.f('ix_crop_market_data_state'), 'crop_market_data', ['state'], unique=False)
    op.create_index(op.f('ix_crop_market_data_year'), 'crop_market_data', ['year'], unique=False)
    op.create_table('crop_profitability',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('crop_type', sa.String(length=100), nullable=False),
    sa.Column('variety', sa.String(length=200), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('season', sa.String(length=50), nullable=True),
    sa.Column('avg_profit_per_acre', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('min_profit_per_acre', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('max_profit_per_acre', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('seed_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('fertilizer_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('pesticide_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('labor_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('irrigation_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('equipment_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('other_costs', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_investment_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('avg_revenue_per_acre', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('roi_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('break_even_yield', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('profit_margin', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=True),
    sa.Column('price_risk_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('yield_risk_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('market_demand', sa.String(length=20), nullable=True),
    sa.Column('competition_level', sa.String(length=20), nullable=True),
    sa.Column('data_source', sa.String(length=100), nullable=True),
    sa.Column('sample_size', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_profitability_location', 'crop_profitability', ['crop_type', 'state', 'district', 'year'], unique=False)
    op.create_index(op.f('ix_crop_profitability_crop_type'), 'crop_profitability', ['crop_type'], unique=False)
    op.create_index(op.f('ix_crop_profitability_district'), 'crop_profitability', ['district'], unique=False)
    op.create_index(op.f('ix_crop_profitability_season'), 'crop_profitability', ['season'], unique=False)
    op.create_index(op.f('ix_crop_profitability_state'), 'crop_profitability', ['state'], unique=False)
    op.create_index(op.f('ix_crop_profitability_year'), 'crop_profitability', ['year'], unique=False)
    op.create_table('crop_recommendations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('recommended_crop', sa.String(length=100), nullable=False),
    sa.Column('variety', sa.String(length=200), nullable=True),
    sa.Column('season', sa.String(length=50), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('recommendation_rank', sa.Integer(), nullable=True),
    sa.Column('expected_profit', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('expected_yield', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('expected_roi', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('opportunity_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('alternative_crops', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('market_reasoning', sa.Text(), nullable=True),
    sa.Column('price_trend', sa.String(length=20), nullable=True),
    sa.Column('demand_level', sa.String(length=20), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=True),
    sa.Column('risk_factors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('planting_window_start', sa.Date(), nullable=True),
    sa.Column('planting_window_end', sa.Date(), nullable=True),
    sa.Column('key_success_factors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('rag_sources', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('rag_embedding', Vector(dim=384), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('farmer_feedback', sa.Text(), nullable=True),
    sa.Column('farmer_rating', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crop_recommendations_farm_id'), 'crop_recommendations', ['farm_id'], unique=False)
    op.create_table('historical_yields',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('crop_type', sa.String(length=100), nullable=False),
    sa.Column('variety', sa.String(length=200), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('block', sa.String(length=100), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('season', sa.String(length=50), nullable=True),
    sa.Column('avg_yield_per_acre', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('min_yield', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('max_yield', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('success_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('farmer_count', sa.Integer(), nullable=True),
    sa.Column('total_area_cultivated', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('soil_types', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('irrigation_methods', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('avg_rainfall', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('avg_temperature', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('quality_distribution', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('avg_quality_grade', sa.String(length=10), nullable=True),
    sa.Column('data_source', sa.String(length=100), nullable=True),
    sa.Column('data_quality_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_yield_location_time', 'historical_yields', ['crop_type', 'state', 'district', 'year', 'season'], unique=False)
    op.create_index(op.f('ix_historical_yields_crop_type'), 'historical_yields', ['crop_type'], unique=False)
    op.create_index(op.f('ix_historical_yields_district'), 'historical_yields', ['district'], unique=False)
    op.create_index(op.f('ix_historical_yields_season'), 'historical_yields', ['season'], unique=False)
    op.create_index(op.f('ix_historical_yields_state'), 'historical_yields', ['state'], unique=False)
    op.create_index(op.f('ix_historical_yields_year'), 'historical_yields', ['year'], unique=False)
    op.create_table('opportunity_costs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('location_state', sa.String(length=100), nullable=False),
    sa.Column('location_district', sa.String(length=100), nullable=True),
    sa.Column('primary_crop', sa.String(length=100), nullable=False),
    sa.Column('alternative_crop', sa.String(length=100), nullable=False),
    sa.Column('season', sa.String(length=50), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('primary_crop_profit', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('alternative_crop_profit', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('profit_difference', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('primary_crop_investment', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('alternative_crop_investment', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('investment_difference', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('primary_crop_roi', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('alternative_crop_roi', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('roi_difference', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('primary_crop_risk', sa.String(length=20), nullable=True),
    sa.Column('alternative_crop_risk', sa.String(length=20), nullable=True),
    sa.Column('risk_factor', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('primary_crop_demand', sa.String(length=20), nullable=True),
    sa.Column('alternative_crop_demand', sa.String(length=20), nullable=True),
    sa.Column('market_stability_comparison', sa.Text(), nullable=True),
    sa.Column('recommended_choice', sa.String(length=100), nullable=True),
    sa.Column('recommendation_confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('recommendation_reasoning', sa.Text(), nullable=True),
    sa.Column('soil_suitability_comparison', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('water_requirement_comparison', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('labor_requirement_comparison', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_crop_comparison', 'opportunity_costs', ['primary_crop', 'alternative_crop'], unique=False)
    op.create_index('idx_opportunity_location', 'opportunity_costs', ['location_state', 'location_district', 'season', 'year'], unique=False)
    op.create_index(op.f('ix_opportunity_costs_alternative_crop'), 'opportunity_costs', ['alternative_crop'], unique=False)
    op.create_index(op.f('ix_opportunity_costs_location_district'), 'opportunity_costs', ['location_district'], unique=False)
    op.create_index(op.f('ix_opportunity_costs_location_state'), 'opportunity_costs', ['location_state'], unique=False)
    op.create_index(op.f('ix_opportunity_costs_primary_crop'), 'opportunity_costs', ['primary_crop'], unique=False)
    op.create_index(op.f('ix_opportunity_costs_season'), 'opportunity_costs', ['season'], unique=False)
    op.create_index(op.f('ix_opportunity_costs_year'), 'opportunity_costs', ['year'], unique=False)
    op.create_table('seasonal_trends',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('crop_type', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('planting_season', sa.String(length=50), nullable=False),
    sa.Column('harvest_season', sa.String(length=50), nullable=True),
    sa.Column('optimal_planting_start', sa.Date(), nullable=True),
    sa.Column('optimal_planting_end', sa.Date(), nullable=True),
    sa.Column('optimal_harvest_start', sa.Date(), nullable=True),
    sa.Column('optimal_harvest_end', sa.Date(), nullable=True),
    sa.Column('avg_growth_duration_days', sa.Integer(), nullable=True),
    sa.Column('price_trend_yoy', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('demand_trend_yoy', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('yield_trend_yoy', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('weather_suitability_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('pest_disease_risk', sa.String(length=20), nullable=True),
    sa.Column('market_timing_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('avg_success_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('farmer_adoption_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('recommended_varieties', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('companion_crops', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('rotation_recommendations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('analysis_start_year', sa.Integer(), nullable=True),
    sa.Column('analysis_end_year', sa.Integer(), nullable=True),
    sa.Column('years_of_data', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_seasonal_location', 'seasonal_trends', ['crop_type', 'state', 'planting_season'], unique=False)
    op.create_index(op.f('ix_seasonal_trends_crop_type'), 'seasonal_trends', ['crop_type'], unique=False)
    op.create_index(op.f('ix_seasonal_trends_planting_season'), 'seasonal_trends', ['planting_season'], unique=False)
    op.create_index(op.f('ix_seasonal_trends_state'), 'seasonal_trends', ['state'], unique=False)
    op.create_table('weather_alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('block', sa.String(length=100), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=11, scale=8), nullable=True),
    sa.Column('alert_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('alert_title', sa.String(length=255), nullable=False),
    sa.Column('alert_description', sa.Text(), nullable=False),
    sa.Column('alert_issued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('event_start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('advance_notice_hours', sa.Integer(), nullable=True),
    sa.Column('weather_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('wind_speed', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('rainfall_expected', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('temperature_min', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('temperature_max', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('humidity', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('affected_crops', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('potential_damage_level', sa.String(length=50), nullable=True),
    sa.Column('impact_description', sa.Text(), nullable=True),
    sa.Column('recommended_actions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('emergency_harvest_recommended', sa.Boolean(), nullable=True),
    sa.Column('protective_measures', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('data_source', sa.String(length=100), nullable=True),
    sa.Column('source_alert_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('is_emergency', sa.Boolean(), nullable=True),
    sa.Column('notification_sent', sa.Boolean(), nullable=True),
    sa.Column('notification_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('farmers_notified_count', sa.Integer(), nullable=True),
    sa.Column('actual_impact', sa.Text(), nullable=True),
    sa.Column('actual_damage_level', sa.String(length=50), nullable=True),
    sa.Column('accuracy_rating', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weather_alerts_alert_type'), 'weather_alerts', ['alert_type'], unique=False)
    op.create_index(op.f('ix_weather_alerts_district'), 'weather_alerts', ['district'], unique=False)
    op.create_index(op.f('ix_weather_alerts_is_emergency'), 'weather_alerts', ['is_emergency'], unique=False)
    op.create_index(op.f('ix_weather_alerts_severity'), 'weather_alerts', ['severity'], unique=False)
    op.create_index(op.f('ix_weather_alerts_state'), 'weather_alerts', ['state'], unique=False)
    op.create_index(op.f('ix_weather_alerts_status'), 'weather_alerts', ['status'], unique=False)
    op.create_table('weather_forecasts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=10, scale=8), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=11, scale=8), nullable=False),
    sa.Column('location_name', sa.String(length=255), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('forecast_date', sa.Date(), nullable=False),
    sa.Column('forecast_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('forecast_type', sa.String(length=50), nullable=True),
    sa.Column('temperature_min', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('temperature_max', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('temperature_avg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('feels_like', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('rainfall_probability', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('rainfall_amount', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('rainfall_intensity', sa.String(length=50), nullable=True),
    sa.Column('wind_speed', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('wind_direction', sa.String(length=50), nullable=True),
    sa.Column('wind_gust', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('humidity', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('pressure', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('dew_point', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('cloud_cover', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('visibility', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('uv_index', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('solar_radiation', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('weather_condition', sa.String(length=100), nullable=True),
    sa.Column('weather_description', sa.Text(), nullable=True),
    sa.Column('weather_icon', sa.String(length=50), nullable=True),
    sa.Column('evapotranspiration', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('soil_moisture_index', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('growing_degree_days', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('data_source', sa.String(length=100), nullable=True),
    sa.Column('source_forecast_id', sa.String(length=255), nullable=True),
    sa.Column('data_quality_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weather_forecasts_district'), 'weather_forecasts', ['district'], unique=False)
    op.create_index(op.f('ix_weather_forecasts_forecast_date'), 'weather_forecasts', ['forecast_date'], unique=False)
    op.create_index(op.f('ix_weather_forecasts_state'), 'weather_forecasts', ['state'], unique=False)
    op.create_table('livestock',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('animal_name', sa.String(length=255), nullable=True),
    sa.Column('animal_tag_id', sa.String(length=100), nullable=True),
    sa.Column('species', sa.String(length=50), nullable=False),
    sa.Column('breed', sa.String(length=100), nullable=False),
    sa.Column('breed_type', sa.String(length=50), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=False),
    sa.Column('color_markings', sa.Text(), nullable=True),
    sa.Column('distinctive_features', sa.Text(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('age_at_acquisition', sa.Integer(), nullable=True),
    sa.Column('current_age_months', sa.Integer(), nullable=True),
    sa.Column('acquisition_date', sa.Date(), nullable=False),
    sa.Column('acquisition_method', sa.String(length=50), nullable=True),
    sa.Column('purchase_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('purchased_from', sa.String(length=255), nullable=True),
    sa.Column('primary_purpose', sa.String(length=50), nullable=False),
    sa.Column('secondary_purposes', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('health_status', sa.String(length=50), nullable=True),
    sa.Column('reproductive_status', sa.String(length=50), nullable=True),
    sa.Column('current_weight', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('height', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('body_condition_score', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('avg_daily_milk_production', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('avg_daily_egg_production', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('lactation_number', sa.Integer(), nullable=True),
    sa.Column('days_in_milk', sa.Integer(), nullable=True),
    sa.Column('breeding_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('number_of_offspring', sa.Integer(), nullable=True),
    sa.Column('last_breeding_date', sa.Date(), nullable=True),
    sa.Column('expected_delivery_date', sa.Date(), nullable=True),
    sa.Column('total_investment', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_feed_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_healthcare_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_other_costs', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_revenue', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('current_market_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('roi_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('break_even_date', sa.Date(), nullable=True),
    sa.Column('days_to_break_even', sa.Integer(), nullable=True),
    sa.Column('monthly_profit', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('housing_type', sa.String(length=100), nullable=True),
    sa.Column('location_on_farm', sa.String(length=255), nullable=True),
    sa.Column('is_insured', sa.Boolean(), nullable=True),
    sa.Column('insurance_provider', sa.String(length=255), nullable=True),
    sa.Column('insurance_policy_number', sa.String(length=100), nullable=True),
    sa.Column('insurance_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('photos', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('documents', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('disposal_date', sa.Date(), nullable=True),
    sa.Column('disposal_method', sa.String(length=50), nullable=True),
    sa.Column('disposal_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('disposal_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_livestock_animal_tag_id'), 'livestock', ['animal_tag_id'], unique=True)
    op.create_index(op.f('ix_livestock_breed'), 'livestock', ['breed'], unique=False)
    op.create_index(op.f('ix_livestock_species'), 'livestock', ['species'], unique=False)
    op.create_index(op.f('ix_livestock_status'), 'livestock', ['status'], unique=False)
    op.create_table('livestock_health_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('animal_id', sa.UUID(), nullable=False),
    sa.Column('record_date', sa.Date(), nullable=False),
    sa.Column('record_type', sa.String(length=100), nullable=False),
    sa.Column('health_status', sa.String(length=50), nullable=True),
    sa.Column('symptoms', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('diagnosis', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=50), nullable=True),
    sa.Column('temperature', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('heart_rate', sa.Integer(), nullable=True),
    sa.Column('respiratory_rate', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('body_condition_score', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('vaccine_name', sa.String(length=255), nullable=True),
    sa.Column('vaccine_type', sa.String(length=100), nullable=True),
    sa.Column('vaccine_batch_number', sa.String(length=100), nullable=True),
    sa.Column('vaccination_site', sa.String(length=100), nullable=True),
    sa.Column('next_vaccination_due', sa.Date(), nullable=True),
    sa.Column('treatment_description', sa.Text(), nullable=True),
    sa.Column('medications', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('dosage', sa.String(length=255), nullable=True),
    sa.Column('treatment_duration_days', sa.Integer(), nullable=True),
    sa.Column('treatment_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('veterinarian_name', sa.String(length=255), nullable=True),
    sa.Column('veterinary_clinic', sa.String(length=255), nullable=True),
    sa.Column('veterinarian_contact', sa.String(length=100), nullable=True),
    sa.Column('prescription', sa.Text(), nullable=True),
    sa.Column('follow_up_required', sa.Boolean(), nullable=True),
    sa.Column('follow_up_date', sa.Date(), nullable=True),
    sa.Column('follow_up_notes', sa.Text(), nullable=True),
    sa.Column('outcome', sa.String(length=50), nullable=True),
    sa.Column('recovery_date', sa.Date(), nullable=True),
    sa.Column('complications', sa.Text(), nullable=True),
    sa.Column('preventive_measures_recommended', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('consultation_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('medication_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('lab_reports', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('prescriptions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('photos', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['animal_id'], ['livestock.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_livestock_health_records_record_date'), 'livestock_health_records', ['record_date'], unique=False)
    op.create_index(op.f('ix_livestock_health_records_record_type'), 'livestock_health_records', ['record_type'], unique=False)
    op.create_table('livestock_roi_predictions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('animal_id', sa.UUID(), nullable=True),
    sa.Column('prediction_date', sa.Date(), nullable=False),
    sa.Column('prediction_type', sa.String(length=50), nullable=True),
    sa.Column('species', sa.String(length=50), nullable=False),
    sa.Column('breed', sa.String(length=100), nullable=False),
    sa.Column('age_months', sa.Integer(), nullable=True),
    sa.Column('purpose', sa.String(length=50), nullable=False),
    sa.Column('purchase_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('initial_setup_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_initial_investment', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('monthly_feed_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('monthly_healthcare_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('monthly_labor_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('monthly_other_costs', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_monthly_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('monthly_milk_revenue', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('monthly_egg_revenue', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('monthly_wool_revenue', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('monthly_manure_revenue', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_monthly_revenue', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('offspring_revenue_per_year', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('expected_sale_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('expected_productive_years', sa.Integer(), nullable=True),
    sa.Column('break_even_months', sa.Integer(), nullable=False),
    sa.Column('break_even_date', sa.Date(), nullable=True),
    sa.Column('roi_1_year', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('roi_2_year', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('roi_5_year', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('roi_percentage_1_year', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('roi_percentage_2_year', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('roi_percentage_5_year', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('monthly_net_profit', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('annual_net_profit', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('lifetime_net_profit', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('comparison_with_alternatives', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('market_price_trends', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=True),
    sa.Column('risk_factors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('mortality_risk', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('disease_risk', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('market_risk', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('key_assumptions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sensitivity_analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('optimization_suggestions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('market_data_source', sa.String(length=100), nullable=True),
    sa.Column('breed_performance_data_source', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['animal_id'], ['livestock.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_livestock_roi_predictions_prediction_date'), 'livestock_roi_predictions', ['prediction_date'], unique=False)
    op.create_table('soil_tests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('plot_id', sa.UUID(), nullable=False),
    sa.Column('test_date', sa.Date(), nullable=False),
    sa.Column('test_type', sa.String(length=100), nullable=True),
    sa.Column('testing_lab', sa.String(length=255), nullable=True),
    sa.Column('lab_report_url', sa.String(length=500), nullable=True),
    sa.Column('soil_type', sa.String(length=50), nullable=True),
    sa.Column('soil_texture', sa.String(length=50), nullable=True),
    sa.Column('soil_color', sa.String(length=50), nullable=True),
    sa.Column('ph_level', sa.Numeric(precision=3, scale=1), nullable=False),
    sa.Column('electrical_conductivity', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('organic_carbon', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('organic_matter', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('nitrogen_n', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('phosphorus_p', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('potassium_k', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('calcium_ca', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('magnesium_mg', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('sulfur_s', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('iron_fe', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('manganese_mn', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('zinc_zn', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('copper_cu', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('boron_b', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('molybdenum_mo', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('nitrogen_status', sa.String(length=20), nullable=True),
    sa.Column('phosphorus_status', sa.String(length=20), nullable=True),
    sa.Column('potassium_status', sa.String(length=20), nullable=True),
    sa.Column('water_holding_capacity', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('drainage_quality', sa.String(length=50), nullable=True),
    sa.Column('bulk_density', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('porosity', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('microbial_activity', sa.String(length=50), nullable=True),
    sa.Column('earthworm_count', sa.Integer(), nullable=True),
    sa.Column('overall_health_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('fertility_rating', sa.String(length=20), nullable=True),
    sa.Column('lab_recommendations', sa.Text(), nullable=True),
    sa.Column('fertilizer_recommendations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('amendment_recommendations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('test_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['plot_id'], ['farm_plots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_soil_tests_test_date'), 'soil_tests', ['test_date'], unique=False)
    op.create_table('crop_monitoring',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('crop_id', sa.UUID(), nullable=False),
    sa.Column('monitoring_date', sa.Date(), nullable=False),
    sa.Column('growth_stage', sa.String(length=50), nullable=True),
    sa.Column('height_cm', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('health_assessment', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('photos', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('weather_conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('farmer_notes', sa.Text(), nullable=True),
    sa.Column('ai_analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('action_items', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['crop_id'], ['crops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fertilizer_applications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('crop_id', sa.UUID(), nullable=False),
    sa.Column('application_date', sa.Date(), nullable=False),
    sa.Column('fertilizer_type', sa.String(length=100), nullable=False),
    sa.Column('fertilizer_name', sa.String(length=200), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('npk_ratio', sa.String(length=20), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('application_method', sa.String(length=100), nullable=True),
    sa.Column('weather_conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('soil_moisture', sa.String(length=50), nullable=True),
    sa.Column('growth_stage', sa.String(length=50), nullable=True),
    sa.Column('expected_results', sa.Text(), nullable=True),
    sa.Column('actual_results', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['crop_id'], ['crops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fertilizer_recommendations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('plot_id', sa.UUID(), nullable=False),
    sa.Column('crop_id', sa.UUID(), nullable=True),
    sa.Column('soil_test_id', sa.UUID(), nullable=True),
    sa.Column('recommendation_date', sa.Date(), nullable=False),
    sa.Column('crop_type', sa.String(length=100), nullable=False),
    sa.Column('crop_growth_stage', sa.String(length=50), nullable=True),
    sa.Column('recommended_fertilizers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('application_schedule', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('nitrogen_requirement', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('phosphorus_requirement', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('potassium_requirement', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('other_nutrients', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('estimated_total_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cost_per_acre', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('expected_yield_increase', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('expected_roi', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('organic_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('chemical_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('recommendation_reasoning', sa.Text(), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('recommendation_source', sa.String(length=100), nullable=True),
    sa.Column('alternative_recommendations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('farmer_feedback', sa.Text(), nullable=True),
    sa.Column('applications_completed', sa.Integer(), nullable=True),
    sa.Column('applications_planned', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['crop_id'], ['crops.id'], ),
    sa.ForeignKeyConstraint(['plot_id'], ['farm_plots.id'], ),
    sa.ForeignKeyConstraint(['soil_test_id'], ['soil_tests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fertilizer_recommendations_recommendation_date'), 'fertilizer_recommendations', ['recommendation_date'], unique=False)
    op.create_table('harvest_recommendations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('crop_id', sa.UUID(), nullable=False),
    sa.Column('weather_alert_id', sa.UUID(), nullable=True),
    sa.Column('recommendation_type', sa.String(length=100), nullable=False),
    sa.Column('recommendation_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('recommended_harvest_date', sa.Date(), nullable=False),
    sa.Column('harvest_window_start', sa.Date(), nullable=False),
    sa.Column('harvest_window_end', sa.Date(), nullable=False),
    sa.Column('urgency_level', sa.String(length=50), nullable=False),
    sa.Column('primary_reason', sa.String(length=100), nullable=True),
    sa.Column('detailed_reasoning', sa.Text(), nullable=False),
    sa.Column('weather_factors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('crop_maturity_factors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('market_factors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('expected_yield', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('expected_quality_grade', sa.String(length=10), nullable=True),
    sa.Column('expected_price_per_unit', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('expected_total_revenue', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('if_harvested_now', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('if_harvested_optimal', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('if_delayed', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('weather_risk_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('quality_risk_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('market_risk_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('overall_risk_level', sa.String(length=50), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('confidence_factors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('estimated_harvest_duration_days', sa.Integer(), nullable=True),
    sa.Column('labor_requirements', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('equipment_requirements', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('storage_requirements', sa.Text(), nullable=True),
    sa.Column('favorable_weather_windows', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('unfavorable_periods', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('market_demand_at_harvest', sa.String(length=50), nullable=True),
    sa.Column('expected_market_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('market_timing_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('farmer_response', sa.String(length=50), nullable=True),
    sa.Column('farmer_feedback', sa.Text(), nullable=True),
    sa.Column('notification_sent', sa.Boolean(), nullable=True),
    sa.Column('notification_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notification_method', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('actual_harvest_date', sa.Date(), nullable=True),
    sa.Column('actual_yield', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('actual_quality_grade', sa.String(length=10), nullable=True),
    sa.Column('actual_price_per_unit', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('actual_total_revenue', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('prediction_accuracy', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('farmer_satisfaction_rating', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['crop_id'], ['crops.id'], ),
    sa.ForeignKeyConstraint(['weather_alert_id'], ['weather_alerts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_harvest_recommendations_status'), 'harvest_recommendations', ['status'], unique=False)
    op.create_table('listings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('crop_id', sa.UUID(), nullable=False),
    sa.Column('farmer_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('crop_type', sa.String(length=100), nullable=False),
    sa.Column('crop_variety', sa.String(length=200), nullable=True),
    sa.Column('estimated_quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('quantity_unit', sa.String(length=20), nullable=True),
    sa.Column('min_quantity', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('max_quantity', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('quality_grade', sa.String(length=10), nullable=True),
    sa.Column('quality_confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('quality_description', sa.Text(), nullable=True),
    sa.Column('expected_harvest_date', sa.Date(), nullable=False),
    sa.Column('harvest_date_confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('harvest_window_start', sa.Date(), nullable=True),
    sa.Column('harvest_window_end', sa.Date(), nullable=True),
    sa.Column('actual_harvest_date', sa.Date(), nullable=True),
    sa.Column('asking_price_per_unit', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_negotiable', sa.Boolean(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('location_state', sa.String(length=100), nullable=False),
    sa.Column('location_district', sa.String(length=100), nullable=False),
    sa.Column('location_block', sa.String(length=100), nullable=True),
    sa.Column('exact_location_shared', sa.Boolean(), nullable=True),
    sa.Column('contact_enabled', sa.Boolean(), nullable=True),
    sa.Column('farmer_phone', sa.String(length=20), nullable=True),
    sa.Column('farmer_email', sa.String(length=255), nullable=True),
    sa.Column('preferred_contact_method', sa.String(length=50), nullable=True),
    sa.Column('market_demand_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('price_trend', sa.String(length=20), nullable=True),
    sa.Column('yoy_price_growth', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('visibility', sa.String(length=50), nullable=True),
    sa.Column('advance_booking_allowed', sa.Boolean(), nullable=True),
    sa.Column('advance_payment_required', sa.Boolean(), nullable=True),
    sa.Column('advance_payment_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('images', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('videos', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('interest_count', sa.Integer(), nullable=True),
    sa.Column('contact_request_count', sa.Integer(), nullable=True),
    sa.Column('listed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['crop_id'], ['crops.id'], ),
    sa.ForeignKeyConstraint(['farmer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('crop_id')
    )
    op.create_index(op.f('ix_listings_crop_type'), 'listings', ['crop_type'], unique=False)
    op.create_index(op.f('ix_listings_expected_harvest_date'), 'listings', ['expected_harvest_date'], unique=False)
    op.create_index(op.f('ix_listings_location_district'), 'listings', ['location_district'], unique=False)
    op.create_index(op.f('ix_listings_location_state'), 'listings', ['location_state'], unique=False)
    op.create_index(op.f('ix_listings_status'), 'listings', ['status'], unique=False)
    op.create_table('soil_amendments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('plot_id', sa.UUID(), nullable=False),
    sa.Column('amendment_date', sa.Date(), nullable=False),
    sa.Column('amendment_type', sa.String(length=100), nullable=False),
    sa.Column('amendment_name', sa.String(length=200), nullable=True),
    sa.Column('primary_purpose', sa.String(length=100), nullable=True),
    sa.Column('target_improvement', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('quantity_per_acre', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('application_method', sa.String(length=100), nullable=True),
    sa.Column('incorporation_depth', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cost_per_acre', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('organic_matter_content', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('nutrient_content', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('carbon_nitrogen_ratio', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('current_ph', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('target_ph', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('expected_ph_change', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('days_before_planting', sa.Integer(), nullable=True),
    sa.Column('soil_moisture_at_application', sa.String(length=50), nullable=True),
    sa.Column('weather_conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('expected_benefits', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('expected_duration_months', sa.Integer(), nullable=True),
    sa.Column('actual_benefits', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('effectiveness_rating', sa.Integer(), nullable=True),
    sa.Column('follow_up_soil_test_id', sa.UUID(), nullable=True),
    sa.Column('recommendation_source', sa.String(length=100), nullable=True),
    sa.Column('recommended_by', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['follow_up_soil_test_id'], ['soil_tests.id'], ),
    sa.ForeignKeyConstraint(['plot_id'], ['farm_plots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_soil_amendments_amendment_date'), 'soil_amendments', ['amendment_date'], unique=False)
    op.create_table('buyer_interests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('listing_id', sa.UUID(), nullable=False),
    sa.Column('buyer_id', sa.UUID(), nullable=False),
    sa.Column('interest_type', sa.String(length=50), nullable=True),
    sa.Column('quantity_interested', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('preferred_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('buyer_phone', sa.String(length=20), nullable=True),
    sa.Column('buyer_email', sa.String(length=255), nullable=True),
    sa.Column('buyer_company', sa.String(length=255), nullable=True),
    sa.Column('quality_requirements', sa.Text(), nullable=True),
    sa.Column('delivery_requirements', sa.Text(), nullable=True),
    sa.Column('payment_terms', sa.Text(), nullable=True),
    sa.Column('contact_requested', sa.Boolean(), nullable=True),
    sa.Column('contact_request_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('contact_approved', sa.Boolean(), nullable=True),
    sa.Column('contact_approved_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('message_to_farmer', sa.Text(), nullable=True),
    sa.Column('farmer_response', sa.Text(), nullable=True),
    sa.Column('last_communication_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_buyer_interests_status'), 'buyer_interests', ['status'], unique=False)
    op.create_table('direct_contacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('listing_id', sa.UUID(), nullable=False),
    sa.Column('buyer_interest_id', sa.UUID(), nullable=True),
    sa.Column('buyer_id', sa.UUID(), nullable=False),
    sa.Column('farmer_id', sa.UUID(), nullable=False),
    sa.Column('contact_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('contact_method', sa.String(length=50), nullable=True),
    sa.Column('farmer_phone_shared', sa.Boolean(), nullable=True),
    sa.Column('buyer_phone_shared', sa.Boolean(), nullable=True),
    sa.Column('agreement_status', sa.String(length=50), nullable=True),
    sa.Column('agreed_quantity', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('agreed_price_per_unit', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('agreed_delivery_date', sa.Date(), nullable=True),
    sa.Column('advance_payment_agreed', sa.Boolean(), nullable=True),
    sa.Column('advance_payment_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('advance_payment_received', sa.Boolean(), nullable=True),
    sa.Column('advance_payment_date', sa.Date(), nullable=True),
    sa.Column('total_transaction_value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('payment_terms', sa.Text(), nullable=True),
    sa.Column('delivery_terms', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('communication_log', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('transaction_completed', sa.Boolean(), nullable=True),
    sa.Column('completion_date', sa.Date(), nullable=True),
    sa.Column('farmer_rating', sa.Integer(), nullable=True),
    sa.Column('buyer_rating', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['buyer_interest_id'], ['buyer_interests.id'], ),
    sa.ForeignKeyConstraint(['farmer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('direct_contacts')
    op.drop_index(op.f('ix_buyer_interests_status'), table_name='buyer_interests')
    op.drop_table('buyer_interests')
    op.drop_index(op.f('ix_soil_amendments_amendment_date'), table_name='soil_amendments')
    op.drop_table('soil_amendments')
    op.drop_index(op.f('ix_listings_status'), table_name='listings')
    op.drop_index(op.f('ix_listings_location_state'), table_name='listings')
    op.drop_index(op.f('ix_listings_location_district'), table_name='listings')
    op.drop_index(op.f('ix_listings_expected_harvest_date'), table_name='listings')
    op.drop_index(op.f('ix_listings_crop_type'), table_name='listings')
    op.drop_table('listings')
    op.drop_index(op.f('ix_harvest_recommendations_status'), table_name='harvest_recommendations')
    op.drop_table('harvest_recommendations')
    op.drop_index(op.f('ix_fertilizer_recommendations_recommendation_date'), table_name='fertilizer_recommendations')
    op.drop_table('fertilizer_recommendations')
    op.drop_table('fertilizer_applications')
    op.drop_table('crop_monitoring')
    op.drop_index(op.f('ix_soil_tests_test_date'), table_name='soil_tests')
    op.drop_table('soil_tests')
    op.drop_index(op.f('ix_livestock_roi_predictions_prediction_date'), table_name='livestock_roi_predictions')
    op.drop_table('livestock_roi_predictions')
    op.drop_index(op.f('ix_livestock_health_records_record_type'), table_name='livestock_health_records')
    op.drop_index(op.f('ix_livestock_health_records_record_date'), table_name='livestock_health_records')
    op.drop_table('livestock_health_records')
    op.drop_index(op.f('ix_livestock_status'), table_name='livestock')
    op.drop_index(op.f('ix_livestock_species'), table_name='livestock')
    op.drop_index(op.f('ix_livestock_breed'), table_name='livestock')
    op.drop_index(op.f('ix_livestock_animal_tag_id'), table_name='livestock')
    op.drop_table('livestock')
    op.drop_index(op.f('ix_weather_forecasts_state'), table_name='weather_forecasts')
    op.drop_index(op.f('ix_weather_forecasts_forecast_date'), table_name='weather_forecasts')
    op.drop_index(op.f('ix_weather_forecasts_district'), table_name='weather_forecasts')
    op.drop_table('weather_forecasts')
    op.drop_index(op.f('ix_weather_alerts_status'), table_name='weather_alerts')
    op.drop_index(op.f('ix_weather_alerts_state'), table_name='weather_alerts')
    op.drop_index(op.f('ix_weather_alerts_severity'), table_name='weather_alerts')
    op.drop_index(op.f('ix_weather_alerts_is_emergency'), table_name='weather_alerts')
    op.drop_index(op.f('ix_weather_alerts_district'), table_name='weather_alerts')
    op.drop_index(op.f('ix_weather_alerts_alert_type'), table_name='weather_alerts')
    op.drop_table('weather_alerts')
    op.drop_index(op.f('ix_seasonal_trends_state'), table_name='seasonal_trends')
    op.drop_index(op.f('ix_seasonal_trends_planting_season'), table_name='seasonal_trends')
    op.drop_index(op.f('ix_seasonal_trends_crop_type'), table_name='seasonal_trends')
    op.drop_index('idx_seasonal_location', table_name='seasonal_trends')
    op.drop_table('seasonal_trends')
    op.drop_index(op.f('ix_opportunity_costs_year'), table_name='opportunity_costs')
    op.drop_index(op.f('ix_opportunity_costs_season'), table_name='opportunity_costs')
    op.drop_index(op.f('ix_opportunity_costs_primary_crop'), table_name='opportunity_costs')
    op.drop_index(op.f('ix_opportunity_costs_location_state'), table_name='opportunity_costs')
    op.drop_index(op.f('ix_opportunity_costs_location_district'), table_name='opportunity_costs')
    op.drop_index(op.f('ix_opportunity_costs_alternative_crop'), table_name='opportunity_costs')
    op.drop_index('idx_opportunity_location', table_name='opportunity_costs')
    op.drop_index('idx_crop_comparison', table_name='opportunity_costs')
    op.drop_table('opportunity_costs')
    op.drop_index(op.f('ix_historical_yields_year'), table_name='historical_yields')
    op.drop_index(op.f('ix_historical_yields_state'), table_name='historical_yields')
    op.drop_index(op.f('ix_historical_yields_season'), table_name='historical_yields')
    op.drop_index(op.f('ix_historical_yields_district'), table_name='historical_yields')
    op.drop_index(op.f('ix_historical_yields_crop_type'), table_name='historical_yields')
    op.drop_index('idx_yield_location_time', table_name='historical_yields')
    op.drop_table('historical_yields')
    op.drop_index(op.f('ix_crop_recommendations_farm_id'), table_name='crop_recommendations')
    op.drop_table('crop_recommendations')
    op.drop_index(op.f('ix_crop_profitability_year'), table_name='crop_profitability')
    op.drop_index(op.f('ix_crop_profitability_state'), table_name='crop_profitability')
    op.drop_index(op.f('ix_crop_profitability_season'), table_name='crop_profitability')
    op.drop_index(op.f('ix_crop_profitability_district'), table_name='crop_profitability')
    op.drop_index(op.f('ix_crop_profitability_crop_type'), table_name='crop_profitability')
    op.drop_index('idx_profitability_location', table_name='crop_profitability')
    op.drop_table('crop_profitability')
    op.drop_index(op.f('ix_crop_market_data_year'), table_name='crop_market_data')
    op.drop_index(op.f('ix_crop_market_data_state'), table_name='crop_market_data')
    op.drop_index(op.f('ix_crop_market_data_season'), table_name='crop_market_data')
    op.drop_index(op.f('ix_crop_market_data_month'), table_name='crop_market_data')
    op.drop_index(op.f('ix_crop_market_data_district'), table_name='crop_market_data')
    op.drop_index(op.f('ix_crop_market_data_crop_type'), table_name='crop_market_data')
    op.drop_index('idx_season_location', table_name='crop_market_data')
    op.drop_index('idx_crop_location_time', table_name='crop_market_data')
    op.drop_table('crop_market_data')
    # ### end Alembic commands ###
