"""add_annual_strategy_and_reminders_tables

Revision ID: 02ce9fcea720
Revises: d35ffb77671d
Create Date: 2026-02-22 17:32:38.216679

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '02ce9fcea720'
down_revision = 'd35ffb77671d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('annual_crop_strategies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('farmer_id', sa.UUID(), nullable=False),
    sa.Column('strategy_year', sa.Integer(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('strategy_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('kharif_crop', sa.String(length=100), nullable=True),
    sa.Column('rabi_crop', sa.String(length=100), nullable=True),
    sa.Column('zaid_crop', sa.String(length=100), nullable=True),
    sa.Column('total_expected_profit', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_investment', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('kharif_implemented', sa.Boolean(), nullable=True),
    sa.Column('rabi_implemented', sa.Boolean(), nullable=True),
    sa.Column('zaid_implemented', sa.Boolean(), nullable=True),
    sa.Column('farmer_rating', sa.Integer(), nullable=True),
    sa.Column('farmer_feedback', sa.Text(), nullable=True),
    sa.Column('actual_results', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.ForeignKeyConstraint(['farmer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_annual_crop_strategies_is_active'), 'annual_crop_strategies', ['is_active'], unique=False)
    op.create_index(op.f('ix_annual_crop_strategies_strategy_year'), 'annual_crop_strategies', ['strategy_year'], unique=False)
    op.create_table('strategy_reminders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('strategy_id', sa.UUID(), nullable=False),
    sa.Column('reminder_type', sa.String(length=50), nullable=False),
    sa.Column('season', sa.String(length=20), nullable=True),
    sa.Column('month', sa.String(length=20), nullable=False),
    sa.Column('action_description', sa.Text(), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=True),
    sa.Column('reminder_date', sa.Date(), nullable=False),
    sa.Column('is_sent', sa.Boolean(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('send_push', sa.Boolean(), nullable=True),
    sa.Column('send_sms', sa.Boolean(), nullable=True),
    sa.Column('send_email', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['strategy_id'], ['annual_crop_strategies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategy_reminders_is_sent'), 'strategy_reminders', ['is_sent'], unique=False)
    op.create_index(op.f('ix_strategy_reminders_reminder_date'), 'strategy_reminders', ['reminder_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_strategy_reminders_reminder_date'), table_name='strategy_reminders')
    op.drop_index(op.f('ix_strategy_reminders_is_sent'), table_name='strategy_reminders')
    op.drop_table('strategy_reminders')
    op.drop_index(op.f('ix_annual_crop_strategies_strategy_year'), table_name='annual_crop_strategies')
    op.drop_index(op.f('ix_annual_crop_strategies_is_active'), table_name='annual_crop_strategies')
    op.drop_table('annual_crop_strategies')
    # ### end Alembic commands ###
