"""File writing utilities with atomic operations and directory management."""

import os
from pathlib import Path
from typing import Optional


def write_file(path: Path | str, content: str, overwrite: bool = True) -> None:
    """
    Write content to file with directory creation and atomic writes.
    
    Args:
        path: File path (relative or absolute)
        content: Content to write
        overwrite: Whether to overwrite existing files (default: True)
        
    Raises:
        FileExistsError: If file exists and overwrite is False
        
    Examples:
        >>> write_file("output/models/farm.py", "class Farm: pass")
        >>> write_file(Path("output/services/farm_service.py"), "# Service code")
    """
    file_path = Path(path) if isinstance(path, str) else path
    
    # Check if file exists and overwrite is disabled
    if file_path.exists() and not overwrite:
        raise FileExistsError(f"File already exists: {file_path}")
    
    # Create parent directories if they don't exist
    file_path.parent.mkdir(parents=True, exist_ok=True)
    
    # Write content atomically using a temporary file
    temp_path = file_path.with_suffix(file_path.suffix + '.tmp')
    
    try:
        # Write to temporary file
        with open(temp_path, 'w', encoding='utf-8') as f:
            f.write(content)
        
        # Atomic rename (replaces existing file if present)
        temp_path.replace(file_path)
        
    except Exception as e:
        # Clean up temporary file on error
        if temp_path.exists():
            temp_path.unlink()
        raise e


def ensure_package(directory: Path | str) -> None:
    """
    Ensure Python package structure with __init__.py files.
    
    Creates the directory and all parent directories if they don't exist,
    and creates an empty __init__.py file in each directory.
    
    Args:
        directory: Directory path to ensure as a Python package
        
    Examples:
        >>> ensure_package("app/models")
        >>> ensure_package(Path("app/api/v1"))
    """
    dir_path = Path(directory) if isinstance(directory, str) else directory
    
    # Create directory and all parents
    dir_path.mkdir(parents=True, exist_ok=True)
    
    # Create __init__.py in this directory
    init_file = dir_path / '__init__.py'
    if not init_file.exists():
        init_file.write_text('', encoding='utf-8')
    
    # Create __init__.py in all parent directories up to the current working directory
    current = dir_path.parent
    cwd = Path.cwd()
    
    while current != cwd and current != current.parent:
        init_file = current / '__init__.py'
        if not init_file.exists():
            init_file.write_text('', encoding='utf-8')
        current = current.parent


def is_auto_generated(file_path: Path | str) -> bool:
    """
    Check if a file is marked as auto-generated.
    
    Args:
        file_path: Path to the file to check
        
    Returns:
        True if file contains auto-generation marker, False otherwise
    """
    path = Path(file_path) if isinstance(file_path, str) else file_path
    
    if not path.exists():
        return False
    
    try:
        with open(path, 'r', encoding='utf-8') as f:
            # Read first 10 lines to check for marker
            for _ in range(10):
                line = f.readline()
                if not line:
                    break
                if 'AUTO-GENERATED' in line or 'auto-generated' in line:
                    return True
    except Exception:
        return False
    
    return False


def add_generation_marker(content: str, schema_name: Optional[str] = None) -> str:
    """
    Add auto-generation marker to file content.
    
    Args:
        content: File content
        schema_name: Optional schema name that generated this file
        
    Returns:
        Content with generation marker prepended
    """
    import datetime
    
    timestamp = datetime.datetime.now().isoformat()
    
    marker = f"""# AUTO-GENERATED FILE
# Generated at: {timestamp}
"""
    
    if schema_name:
        marker += f"# Schema: {schema_name}\n"
    
    marker += "# Do not edit this file manually - changes will be overwritten\n\n"
    
    return marker + content
