export interface Supply_match {
   id: number,
   created_at: Date,
   updated_at: Date,
   enable: number,
   request_id: number,
   listing_id: number | null,
   farmer_id: number,
   matched_quantity: number,
   match_score: number | null,
   price_offered: number | null,
   status: string,
   match_explanation: text | null,
   is_aggregated: boolean,
   aggregation_group_id: string | null,
   farmer_confirmation_status: string,
   farmer_confirmed_at: Date | null,
   buyer_accepted_at: Date | null,
   delivery_status: string,
   delivery_notes: text | null,
   active_role_id: number,
   active_role_id: number,
   active_role_id: number
}