export interface Transport_booking {
   id: number,
   created_at: Date,
   updated_at: Date,
   enable: number,
   transaction_id: number,
   provider_id: number,
   requester_id: number,
   pickup_address: text,
   pickup_latitude: number | null,
   pickup_longitude: number | null,
   delivery_address: text,
   delivery_latitude: number | null,
   delivery_longitude: number | null,
   distance_km: number,
   livestock_type: string,
   livestock_count: number,
   animal_value: number,
   transport_cost: number,
   insurance_opted: boolean | null,
   insurance_cost: number | null,
   total_cost: number,
   scheduled_pickup_date: Date,
   estimated_delivery_date: Date,
   actual_pickup_date: Date | null,
   actual_delivery_date: Date | null,
   status: string | null,
   tracking_updates: text | null,
   special_instructions: text | null,
   rating: number | null,
   review: text | null,
   reviewed_at: Date | null,
   cancelled_at: Date | null,
   cancellation_reason: text | null,
   active_role_id: number,
   active_role_id: number,
   active_role_id: number
}